// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xt1JFBlLef1gDmH_sP0EPm-bK02b__k',
    appId: '1:237548170950:web:255fd6a7624940dbdd31c7',
    messagingSenderId: '237548170950',
    projectId: 'morningmate-11c87',
    authDomain: 'morningmate-11c87.firebaseapp.com',
    storageBucket: 'morningmate-11c87.firebasestorage.app',
    measurementId: 'G-8MQESV8C8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIl1ObbqcPM56aGWCx8E9J_9EySE1Bm0o',
    appId: '1:237548170950:android:89f17d0cc9dff63edd31c7',
    messagingSenderId: '237548170950',
    projectId: 'morningmate-11c87',
    storageBucket: 'morningmate-11c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOnoVHlRmJ3nN2ecWpOyfeMlqxANOzKlw',
    appId: '1:237548170950:ios:ef136093df836e4fdd31c7',
    messagingSenderId: '237548170950',
    projectId: 'morningmate-11c87',
    storageBucket: 'morningmate-11c87.firebasestorage.app',
    androidClientId: '237548170950-eikhniv3piqlj3quh5bm7mfeh73lps9v.apps.googleusercontent.com',
    iosClientId: '237548170950-gspdk280eifqjb7140kba89bqikn79ol.apps.googleusercontent.com',
    iosBundleId: 'com.stlim1025.morningmate',
  );
}
