import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'account': 'Account',
      'changeNickname': 'Change Nickname',
      'email': 'Email',
      'security': 'Security',
      'biometricAuth': 'Biometric Auth',
      'biometricAuthDescEnabled': 'Biometric auth required',
      'biometricAuthDescDisabled': 'Protect app with biometric auth',
      'changePassword': 'Change Password',
      'appSettings': 'App Settings',
      'writingBlur': 'Writing Blur Default',
      'writingBlurDescEnabled': 'Blur writing by default',
      'writingBlurDescDisabled': 'Show writing by default',
      'notificationSettings': 'Notification Settings',
      'language': 'Language',
      'info': 'Info',
      'versionInfo': 'Version Info',
      'termsOfService': 'Terms of Service',
      'privacyPolicy': 'Privacy Policy',
      'logout': 'Logout',
      'deleteAccount': 'Delete Account',
      'nicknamePlaceholder': 'Enter nickname (2-10 chars)',
      'cancel': 'Cancel',
      'change': 'Change',
      'confirm': 'Confirm',
      'retry': 'Retry',
      'error': 'Error',
      'nicknameLengthError': 'Nickname must be at least 2 characters',
      'nicknameTakenError': 'Nickname is already taken',
      'korean': 'Korean',
      'english': 'English',
      'selectLanguage': 'Select Language',
      'collectMyMemos': 'Collect My Memos',
      'myPage': 'My Page',
      'diaryWritingInfo': 'Diary Writing Info',
      'branch': 'Branch',
      'home': 'Home',
      'challenge': 'Challenge',
      'friends': 'Friends',
      'shop': 'Shop',
      'buyItem': 'Purchase',
      'writeDiary': 'Write Diary',
      'wallpaper': 'Wallpaper',
      'background': 'Background',
      'prop': 'Prop',
      'floor': 'Floor',
      'character': 'Character',
      'emoticon': 'Emoticon',
      'watchAdGetBranch': 'Watch Ad Get 10 Branches',
      'completed': 'Completed',
      'watch': 'Watch',
      'unowned': 'Unowned',
      'purchaseConfirm': 'Do you want to purchase {item}?',
      'salePrice': 'SALE! {original} -> {discounted} Branch',
      'notEnoughBranch': 'Not enough branches.',
      'purchaseSuccess': '{item} purchased.',
      'decorate': 'Decorate',
      'owned': 'Owned',
      'sale': 'SALE',
      'notifications': 'Notifications',
      'markAllAsRead': 'Mark all as read',
      'loadingNotifications': 'Loading notifications...',
      'pleaseWait': 'Please wait',
      'errorLoadingNotifications': 'Error loading notifications',
      'tryAgainLater': 'Please try again later',
      'noNotifications': 'No notifications',
      'noNotificationsDesc': 'We will notify you when there is news',
      'replyFrom': 'Reply from {username}',
      'cheerFrom': 'Cheer from {username}',
      'wakeUpAlert': 'Wake up alert',
      'nestPokeAlert': 'Nest Poke',
      'friendRequest': 'Friend Request',
      'accept': 'Accept',
      'reject': 'Reject',
      'replyCompleted': 'Replied',
      'reply': 'Reply',
      'stickyNoteHint': 'Leave a short message',
      'decorateRoom': 'Decorate Room',
      'decorationSaved': 'Settings saved! ✨',
      'saveFailed': 'Save failed: ',
      'save': 'Save',
      'noProps': 'You don\'t have any props. Buy some in the shop!',
      'stickyNoteLimit': 'You can only write a note once a day. ✍️',
      'noStickyNote':
          'You don\'t have a sticky note. Please buy one from the shop. 📦',
      'deleteStickyNote': 'Do you want to delete this memo? 🗑️',
      'stickyNoteAdded': 'Memo added! (30 points deducted) 📝',
      'notEnoughPoints': 'Not enough points! (30 required)',
      // Main & Strings
      'greetingMorning': 'Good morning!',
      'greetingAfternoon': 'Good afternoon!',
      'greetingEvening': 'Good evening!',
      'consecutiveDays': '{days} days consecutive streak 🔥',
      'nicknameIntro': 'Nice to meet you! Please enter your nickname.',
      'start': 'Start',
      'kakaoLogin': 'Kakao Login',
      'appleLogin': 'Apple Login',
      'nicknameChanged': 'Nickname changed! ✨',
      'errorSavingSettings': 'Error saving settings: ',
      'enterNewNickname': 'Enter new nickname',
      // Social
      'friendsTitle': 'Friends',
      'friendsCount': '{count}',
      'addFriendEmpty': 'Add a friend',
      'newFriendRequests': 'New friend requests',
      'friendRequestSent': 'Friend request sent to {nickname}!',
      'youBecameFriends': 'You became friends with {nickname}!',
      'enterFriendNickname': 'Enter friend nickname',
      'request': 'Request',
      'invite': 'Invite',
      'userNotFound': 'User not found.',
      'selfRequestError': 'You cannot send a request to yourself.',
      'addFriendButton': '+ Add Friend',
      'friendRequestRejection': 'Friend request rejected.',
      'wakeUp': 'Wake Up',
      'written': 'Written',
      'wakeUpSuccess': 'You woke up {nickname}! ⏰',
      'wakeUpFailed': 'Failed to wake up friend.',
      'secondsUnit': '{seconds}s',
      // Challenge
      'challengesTitle': 'Challenges',
      'challengesProgress': 'Challenges Completed',
      'challengeCompleted': 'Challenge Completed!',
      'challengeDetailCurrent': 'Current',
      'challengeDetailTarget': 'Target',
      'challengeDetailInfo': 'Challenge Details',
      'challengeDetailWarningTitle': 'Caution',
      'challengeDetailWarningDesc':
          'If you miss even one day, the consecutive record resets to 0!',
      'challengeDetailCurrentRecord': 'Current Record',
      'challengeDetailRemaining': 'Remaining in this series',
      'challengeDetailReward': 'Reward',
      'challengeDetailCurrentLabel': 'Current',
      'challenge_dawn_start_title': 'Start of Dawn',
      'challenge_dawn_start_desc': 'Write a diary before 6 AM once',
      'challenge_steady_habit_title': 'Steady Habit',
      'challenge_steady_habit_desc': 'Write diary for 3 consecutive days',
      'challenge_morning_person_title': 'True Morning Person',
      'challenge_morning_person_desc': 'Write diary for 7 consecutive days',
      'challenge_rich_room_title': 'Rich Room',
      'challenge_rich_room_desc': 'Buy 3 or more props',
      'challenge_social_king_title': 'Social King',
      'challenge_social_king_desc': 'Make 5 friends',
      'challenge_diary_master_title': 'Diary Master',
      'challenge_diary_master_desc': 'Write 30 diaries in total',
      'challenge_streak_14_title': '2 Weeks Streak',
      'challenge_streak_14_desc': 'Write diary for 14 consecutive days',
      'challenge_streak_21_title': '3 Weeks Streak',
      'challenge_streak_21_desc': 'Write diary for 21 consecutive days',
      'challenge_streak_30_title': 'Monthly Master',
      'challenge_streak_30_desc': 'Write diary for 30 consecutive days',
      'challenge_friend_1_title': 'First Friend',
      'challenge_friend_1_desc': 'Make your first friend',
      'challenge_friend_10_title': 'Popular',
      'challenge_friend_10_desc': 'Make 10 friends',
      'challenge_friend_20_title': 'Social Celebrity',
      'challenge_friend_20_desc': 'Make 20 friends',
      'challenge_prop_1_title': 'First Decoration',
      'challenge_prop_1_desc': 'Buy 1 prop',
      'challenge_prop_5_title': 'Decorator',
      'challenge_prop_5_desc': 'Buy 5 props',
      'challenge_prop_10_title': 'Maximalist',
      'challenge_prop_10_desc': 'Buy 10 props',
      'challenge_fashion_3_title': 'Fashionista',
      'challenge_fashion_3_desc': 'Buy 3 character items',
      'challenge_fashion_5_title': 'Trendsetter',
      'challenge_fashion_5_desc': 'Buy 5 character items',
      'challenge_bg_1_title': 'Mood Change',
      'challenge_bg_1_desc': 'Buy 1 background',
      'challenge_bg_3_title': 'Atmosphere Master',
      'challenge_bg_3_desc': 'Buy 3 backgrounds',
      'challenge_level_2_title': 'First Growth',
      'challenge_level_2_desc': 'Reach Character Level 2',
      'challenge_level_3_title': 'Growing Up',
      'challenge_level_3_desc': 'Reach Character Level 3',
      'challenge_level_4_title': 'Almost There',
      'challenge_level_4_desc': 'Reach Character Level 4',
      'challenge_level_5_title': 'Fully Grown',
      'challenge_level_5_desc': 'Reach Character Level 5',
      'challenge_memo_1_title': 'First Memo',
      'challenge_memo_1_desc': 'Write your first memo',
      'challenge_memo_3_title': 'Memo Collector',
      'challenge_memo_3_desc': 'Write 3 memos',
      'challenge_memo_10_title': 'Memo Maniac',
      'challenge_memo_10_desc': 'Write 10 memos',
      'challenge_memo_30_title': 'Memo Master',
      'challenge_memo_30_desc': 'Write 30 memos',
      'deleteAccountConfirmDesc':
          'Are you sure you want to delete your account?\nAll data will be permanently deleted.',
      'passwordConfirmHint': 'Verify Password',
      'deleteAccountConsent':
          'I have read the notices and agree to delete my account.',
      'noDiaryForDay': 'No diary recorded for this day',
      'diaryRecordForDay': '{date} Record',
      'biometricAuthReasonPastRecords':
          'Authentication required to view past records',
      'biometricAuthFailed': 'Biometric authentication failed. 🔒',
      'noMemos': 'No memos written',
      'myMemos': 'My Memos',
      'fullDateFormat': '{year}.{month}.{day} ({weekday})',
      'monthDayFormat': '{month}.{day}',
      'monthDayFormatWithWeekday': '{month}.{day} ({weekday})',
      'state_egg': 'Egg 🥚',
      'state_cracking': 'Cracking Egg 🥚✨',
      'state_hatching': 'Hatching 🐣',
      'state_baby': 'Baby Bird 🐥',
      'state_young': 'Young Bird 🐦',
      'state_adult': 'Cute Bird 🕊️',
      'state_sleeping': 'Sleeping 💤',
      'weekday_mon': 'Mon',
      'weekday_tue': 'Tue',
      'weekday_wed': 'Wed',
      'weekday_thu': 'Thu',
      'weekday_fri': 'Fri',
      'weekday_sat': 'Sat',
      'weekday_sun': 'Sun',
      'noQuestion': 'No question.',
      'previous': 'Previous',
      'next': 'Next',
      'characterInfo': 'Character Info',
      // AppDialog
      'biometricErrorTitle': 'Biometric Auth Failed',
      'biometricErrorDesc':
          'Biometric authentication failed. Please try again or logout.',
      'logoutTitle': 'Logout',
      'logoutDesc': 'Are you sure you want to logout?',
      'deleteAccountTitle': 'Delete Account',
      'deleteAccountDesc':
          'Are you sure you want to delete your account?\nAll data will be deleted and cannot be recovered.',
      'addFriendTitle': 'Add Friend',
      'cheerMessageTitle': 'Cheer Message',
      'exitWritingTitle': 'Stop Writing?',
      'sentMessagesTitle': 'Sent Messages',
      'purchaseTitle': 'Purchase Item',
      'purchaseCompleteTitle': 'Purchase Complete',
      'levelUpTitle': '🎊 Congratulations! 🎊',
      'levelUpDesc':
          'Your character has grown to a new level!\nPlease continue to help them grow.',
      'continueGrowth': 'Please continue to help them grow.',
      'maxLevel': 'Max Level',
      'adRewardTitle': 'Branch Earned!',
      'adRewardDesc': 'You earned 10 branches for watching the ad!',
      'deleteFriendTitle': 'Delete Friend',
      'deleteFriendDesc': 'Are you sure you want to delete this friend?',
      'reportTitle': 'Report',
      'report': 'Report',
      'ok': 'OK',
      'close': 'Close',
      // Items (Names)
      'item_name_default': 'Basic',
      'item_name_stripe': 'Stripe',
      'item_name_check': 'Check',
      'item_name_dot': 'Dot',
      'item_name_flower_sky': 'Flower Sky',
      'item_name_pink_lace': 'Pink Lace',
      'item_name_red_heart': 'Red Heart',
      'item_name_colorful_hexagon': 'Colorful Hexagon',
      'item_name_Space_Background': 'Space',
      'item_name_Castle_Stone_Wall': 'Medieval Castle Wall',
      'item_name_lego_wallpaper': 'Block Wallpaper',
      'item_name_DarkPanel': 'Dark Panel',
      'item_name_IvoryClassic': 'Ivory Classic',
      'item_name_light': 'Light',
      'item_name_happy': 'Happy',
      'item_name_normal': 'Normal',
      'item_name_sad': 'Sad',
      'item_name_love': 'Love',
      'item_name_angry': 'Angry',
      'item_name_awkward': 'Awkward',
      'item_name_move': 'Touched',
      'item_name_sleep': 'Sleepy',
      'item_name_blue_moon': 'Blue Moon',
      'item_name_blue_moon2': 'Blue Moon 2',
      'item_name_golden_sun': 'Golden Sun',
      'item_name_starry_night': 'Starry Night',
      'item_name_alarm_clock': 'Alarm Clock',
      'item_name_wood_desk': 'Wood Desk',
      'item_name_book_desk': 'Reading Desk',
      'item_name_wooden_desk_sprite': 'Wood Desk 2',
      'item_name_space_desk': 'Space Desk',
      'item_name_space_desk2': 'Space Desk 2',
      'item_name_space_drawer': 'Space Drawer',
      'item_name_space_drawer2': 'Space Drawer 2',
      'item_name_wood_chair': 'Wood Chair',
      'item_name_wood_bed': 'Wood Bed',
      'item_name_space_chair': 'Space Chair',
      'item_name_space_bed': 'Space Bed',
      'item_name_pogeun_sofa': 'Cozy Sofa',
      'item_name_cozy_bean': 'Nap Sofa',
      'item_name_pot_1': 'Plant Pot',
      'item_name_analog_clock': 'Analog Clock',
      'item_name_white_bear': 'White Bear',
      'item_name_pink_chair': 'Pink Chair',
      'item_name_blue_chair': 'Blue Chair',
      'item_name_mug_cup': 'Mug Cup',
      'item_name_wood_cup': 'Wood Cup',
      'item_name_cloud_watch': 'Cloud Clock',
      'item_name_red_carpet': 'Red Carpet',
      'item_name_sticky_note': 'Memo Note',
      'item_name_wood': 'Wood Floor',
      'item_name_wood2': 'Wood Floor 2',
      'item_name_pink_wood': 'Pink Wood Floor',
      'item_name_peach_break': 'Peach Pitch',
      'item_name_pink_carpet': 'Pink Carpet',
      'item_name_alokdalok': 'Colorful',
      'item_name_castle_stone': 'Medieval Stone Floor',
      'item_name_space_floor': 'Space Floor',
      'item_name_lego_book_desk': 'Block Book Desk',
      'item_name_lego_chair': 'Block Chair',
      'item_name_lego_clock': 'Block Clock',
      'item_name_lego_cloth_desk': 'Block Cloth Desk',
      'item_name_lego_desk': 'Block Desk',
      'item_name_lego_door': 'Block Door',
      'item_name_lego_flower': 'Block Flower',
      'item_name_lego_frame': 'Block Frame',
      'item_name_lego_frame2': 'Block Frame 2',
      'item_name_lego_game_machine': 'Block Game Machine',
      'item_name_lego_lamp': 'Block Lamp',
      'item_name_lego_mailbox': 'Block Mailbox',
      'item_name_lego_piano': 'Block Piano',
      'item_name_lego_sink': 'Block Sink',
      'item_name_lego_floor': 'Block Floor',
      'item_name_DarkWood_Floor': 'Dark Wood Floor',
      'item_name_lego_lug': 'Block Rug',
      'item_name_wall_lamp': 'Wall Lamp',
      'item_name_warm_lamp': 'Warm Lamp',
      // Login & Auth
      'login': 'Login',
      'signup': 'Sign Up',
      'emailPlaceholder': 'Email',
      'passwordPlaceholder': 'Password',
      'loginWithGoogle': 'Continue with Google',
      'loginWithKakao': 'Continue with Kakao',
      'loginWithApple': 'Continue with Apple',
      'loginWithID': 'Login with ID',
      'idLogin': 'ID Login',
      'noAccountSignup': 'Don\'t have an account? Sign Up',
      'alreadyHaveAccountLogin': 'Already have an account? Login',
      'emailRequired': 'Please enter email',
      'emailInvalid': 'Invalid email format',
      'passwordRequired': 'Please enter password',
      'passwordLengthError': 'Password must be at least 6 characters',
      'namePlaceholder': 'Name',
      'nameRequired': 'Please enter name',
      'passwordConfirmPlaceholder': 'Confirm Password',
      'passwordMismatch': 'Passwords do not match',
      'signupSuccess': 'Sign up successful! Please login.',
      'loginError': 'Login failed',
      'signupError': 'Sign up failed',
      'introTitle': 'Morni',
      'introSubtitle': 'Your mate for the morning',
      // Notification Settings
      'serviceNotification': 'Service Notifications',
      'morningDiaryNoti': 'Morning Diary Alert',
      'morningDiaryNotiDesc': 'Remind you to write diary every morning',
      'activityNotification': 'Activity Notifications',
      'wakeUpNoti': 'Wake Up Alert',
      'wakeUpNotiDesc': 'Get notified when a friend wakes you up',
      'cheerMessageNoti': 'Cheer Message Alert',
      'cheerMessageNotiDesc': 'Get notified when a friend sends a cheer',
      'friendNotification': 'Friend Notifications',
      'friendRequestNoti': 'Friend Request Alert',
      'friendRequestNotiDesc': 'Get notified of new friend requests',
      'friendAcceptNoti': 'Friend Accept Alert',
      'friendAcceptNotiDesc': 'Get notified when your request is accepted',
      'friendRejectNoti': 'Friend Reject Alert',
      'friendRejectNotiDesc': 'Get notified when your request is rejected',
      'notificationTime': 'Notification Time',
      'timePickerHour': 'H',
      'timePickerMinute': 'M',
      'nestNotification': 'Nest Notifications',
      'nestInviteNoti': 'Nest Invite Alert',
      'nestInviteNotiDesc': 'Get notified when you receive a nest invite',
      'nestDonationNoti': 'Nest Donation Alert',
      'nestDonationNotiDesc':
          'Get notified when a nest member donates branches',
      // Writing Screen
      'tempSave': 'Draft',
      'saveDraft': 'Save Draft',
      'saveDraftSuccess': 'Draft saved. 📝',
      'saveDraftError': 'Error saving draft. ⚠️',
      'saveDiarySuccess': 'Diary saved! Character woke up! ☀️',
      'saveDiaryError': 'Error saving diary. ⚠️',
      'diaryCompletionTitle': 'Character Woke Up!',
      'diaryCompletionDesc': 'Your character has started the day!',
      'branchEarned': '+{amount} Branch Earned',
      'exitConfirmation': 'Stop Writing?',
      'exitConfirmationDesc': 'Unsaved content will be lost.',
      'keepWriting': 'Keep Writing',
      'stop': 'Stop',
      'writingHint': 'Write down whatever comes to your mind freely.',
      'todayQuestion': 'Today\'s Question',
      'moreWriting': 'Please write a bit more! ✍️',
      'authRequiredForSave': 'Authentication required to save diary',
      'authFailedForSave': 'Authentication failed. Cannot save diary. 🔒',
      // Archive & Diary Detail
      'diaryContent': 'Diary Content',
      'encryptedDiary': 'Encrypted Diary',
      'diaryLoadError': 'Failed to load diary content.',
      'noDiaryContent': 'No diary content.',
      'emotionalAnalysis': 'Emotional Analysis',
      'totalDiaries': 'Total Diaries',
      'consecutiveDaysLabel': 'Consecutive',
      'days': ' Days',
      // Common
      'edit': 'Edit',
      'yes': 'Yes',
      'no': 'No',
      'equipped': 'Equipped',
      'stampEquipped': 'Equipped',
      'unequipped': 'Unequipped',
      'item_name_heart_glass': 'Heart Glasses',
      'item_name_blue_ribbon': 'Blue Ribbon',
      'item_name_pink_mupler': 'Pink Scarf',
      'item_name_necktie': 'Necktie',
      'item_name_plogeyes': 'Frog Eyes',
      'item_name_sprout': 'Sprout',
      'item_name_crown': 'Crown',
      'item_name_wood_glass': 'Wood Glasses',
      'item_name_space_clothes': 'Space Suit',
      'item_name_prog_clothes': 'Frog Suit',
      'item_name_superb_bird_clothes': 'Superb Bird Suit',
      'item_name_humming_bird_clothes': 'Hummingbird Suit',
      'item_name_knight_helm': 'Knight Helm',
      'item_name_castle_candle': 'Castle Candle',
      'item_name_castle_knight_statue': 'Knight Statue',
      'item_name_castle_treasure_chest': 'Treasure Chest',
      'item_name_castle_gargoyle_statue': 'Gargoyle Statue',
      'decorateCharacter': 'Decorate Character',
      'unequipAll': 'Unequip All',
      'removeAllProps': 'Remove All',
      'showOwnedOnly': 'Show Owned Only',
      'bulkPurchase': 'Bulk Purchase',
      'bulkPurchaseConfirm':
          'There are unowned items.\nDo you want to purchase them all?',
      'totalPrice': 'Total: ',
      'purchaseAndSaveSuccess': 'Purchase & Save Complete! ✨',
      'all': 'All',
      'head': 'Head',
      'face': 'Face',
      'clothes': 'Clothes',
      'accessory': 'Accessory',
      'viewDiaryContent': 'View Diary Content',
      'suspensionTitle': 'Suspension Notice',
      'unsuspendTitle': 'Unsuspend User',
      'suspensionContent':
          'Service access has been temporarily restricted due to community guideline violations.',
      'remainingTimeTitle': 'Time remaining until lifted',
      'permanentSuspension': 'Permanent Suspension',
      'daysRemaining': '{days}d {hours}h remaining',
      'hoursRemaining': '{hours}h {minutes}m remaining',
      'minutesRemaining': '{minutes}m remaining',
      'suspensionReason': 'Reason: {reason}',
      'reason_community_violation': 'Community Guideline Violation',
      // Friend Room
      'sendCheerMessage': 'Send Cheer',
      'resendAfterSeconds': 'Resend in {seconds}s',
      'sentHistory': 'Sent History',
      'friend': 'friend',
      'cheerMessageHint': 'Leave a cheer message',
      'cheerMessageSent': 'Cheer message sent! 💌',
      'cheerMessageSendFailed': 'Failed to send cheer message.',
      'leave': 'Leave',
      'noSentMessages': 'No messages sent yet',
      'userReport': 'User Report',
      'reportReasonSelect': 'Please select a reason.',
      'reportSubmitted': 'Report submitted.',
      'reportError': 'Error submitting report.',
      'reportReasonInappropriate': 'Inappropriate Content',
      'reportReasonAbusive': 'Abusive Language',
      'reportReasonSpam': 'Spam/Ads',
      'reportReasonOther': 'Other',
      'deleteFriendConfirm':
          'Do you want to delete {nickname} from your friend list?',
      'delete': 'Delete',
      'friendDeleted': 'Friend deleted.',
      'friendDeleteError': 'Error deleting friend.',
      // Nest Room
      'nest': 'Nest',
      'nestList': 'Nest List',
      'participatingNests': 'Participating Nests',
      'myNests': 'My Nests',
      'createNest': '+ Create Nest',
      'nestLevel': 'Lv.{level}',
      'nestPeopleCount': '{current}/{max}',
      'createdAt': 'Created At',
      'lastActivity': 'Last activity: {time}',
      'todayActivity': 'Today activity',
      'yesterdayActivity': 'Yesterday activity',
      'hoursAgo': '{hours} hours ago',
      'minutesAgo': '{minutes} minutes ago',
      'justNow': 'Just now',
      'recentActivity': 'Recent activity',
      'createNestTitle': 'Create Nest',
      'nestName': 'Nest Name',
      'enterNestName': 'Enter nest name',
      'maxPeople': 'Max People',
      'isPublic': 'Public/Private',
      'public': 'Public',
      'private': 'Private',
      'create': 'Create',
      'memo': 'Memo',
      'unknown': 'Unknown',
      'nestEditTitle': 'Edit Nest',
      'collectGajiTitle': 'Collect Branches',
      'nestInvitePopupTitle': 'Nest Invite',
      'nestCreateTitle': 'Create Nest',
      'nestNoParticipating': 'No nests joined yet',
      'nestNoMyNests': 'No nests created yet',
      'nestCreateNew': 'Create a new nest!',
      'nestInviteButton': '+ Invite to Nest',
      'nestPlaceholderDesc': 'Our nest story',
      'nestActivityJustNow': 'Just now',
      'nestActivityDaysAgo': '{days} days ago',
      'nestActivityHoursAgo': '{hours} hours ago',
      'nestActivityMinutesAgo': '{minutes} minutes ago',
      'nestEnter': 'Enter >',
      'nestInvite': 'Nest Invite',
      'nestDonation': 'Nest Donation',
      'nestInviteTitle': 'New Nest Invite',
      'nestLabel': 'Nest: {name}',
      'nestInvitePlaceholder': 'Enter friend nickname to invite',
      'nestSelfInviteError': 'You cannot invite yourself.',
      'nestUserNotFoundError': 'User not found.',
      'nestAlreadyMemberError': 'User is already in the nest.',
      'nestInviteSent': 'Invite sent to {nickname}.',
      'nestInviteFailed': 'Invite failed: {error}',
      'nestCollectHint': 'Enter amount to collect',
      'nestCollectButton': 'Collect',
      'nestInvalidAmount': 'Please enter a valid number.',
      'nestNotEnoughGaji': 'Cannot collect more than you have.',
      'nestCollectSuccessTitle': 'Collect Complete',
      'nestCollectSuccessDesc': 'Collected {amount} branches!',
      'nestManageTitle': 'Manage Nest',
      'nestNameHint': 'Enter nest name',
      'nestDescHint': 'Enter nest description (max 15 chars)',
      'nestUpdateSuccess': 'Nest info updated!',
      'nestCreateSuccess': 'Nest created! ✨',
      'nestMyStreak': 'My streak: {days} days!',
      'nestPokeCooldown': 'Wait! Resend in {seconds}s.',
      'nestPokeSuccess': 'Poked {nickname}!',
      'nestPokeDescription': '{nickname}: {days} days streak!',
      'nestNoMembers': 'No members yet.',
      'errorOccurred': 'An error occurred.',
      'dayUnit': 'd',
      'nestMaxCountError': 'You can only create up to 2 nests.',
      'nestInvalidDonateAmount':
          'Please enter a valid amount of branches to donate.',
      'nestNotEnoughGajiError': 'Not enough branches in your account.',
      'nestEmptyMessageError': 'Please enter a message.',
      'nestEmptyNameError': 'Please enter a nest name.',
      'nestFullTitle': 'Nest Full',
      'nestFullError': 'The nest is full and you cannot join.',
      'nestLeaveConfirm': 'Do you want to leave \'{name}\' nest?',
      'nestDeleteConfirm':
          'Do you want to delete \'{name}\' nest?\nAll members will be removed and cannot be recovered.',
      'nestLeaveTitle': 'Leave Nest',
      'nestDeleteTitle': 'Delete Nest',
      'nestDeleteSuccess': 'Nest deleted.',
      'nestLeaveSuccess': 'You left the nest.',
      'nestWithdraw': 'Leave',
      'nestUpgradeTitle': 'Nest Upgrade',
      'nestUpgradeConfirm':
          'Would you like to upgrade your nest to Level 2?\nThe background will change and the member limit will increase to 15.',
      'nestUpgradeSuccess': 'The nest has been upgraded to Level 2!',
      'nestUpgrade': 'Upgrade',
      'upgrade': 'Upgrade',
    },
    'ko': {
      'settings': '설정',
      'account': '계정',
      'changeNickname': '닉네임 변경',
      'email': '이메일',
      'security': '보안',
      'biometricAuth': '생체 인증',
      'biometricAuthDescEnabled': '앱 실행 시 인증 필수',
      'biometricAuthDescDisabled': '생체 인증으로 앱 보호',
      'changePassword': '비밀번호 변경',
      'appSettings': '앱 설정',
      'writingBlur': '글 작성 블러 기본값',
      'writingBlurDescEnabled': '기본적으로 일기 내용 가림',
      'writingBlurDescDisabled': '기본적으로 일기 내용 표시',
      'notificationSettings': '알림 설정',
      'language': '언어',
      'info': '정보',
      'versionInfo': '버전 정보',
      'termsOfService': '이용약관',
      'privacyPolicy': '개인정보 처리방침',
      'logout': '로그아웃',
      'deleteAccount': '회원탈퇴',
      'nicknamePlaceholder': '새 닉네임 입력',
      'cancel': '취소',
      'change': '변경',
      'confirm': '확인',
      'retry': '다시 시도',
      'error': '오류',
      'nicknameLengthError': '닉네임은 2자 이상이어야 합니다',
      'nicknameTakenError': '이미 사용 중인 닉네임입니다',
      'korean': '한국어',
      'english': 'English',
      'selectLanguage': '언어 선택',
      'collectMyMemos': '내 메모 모아보기',
      'myPage': '마이페이지',
      'diaryWritingInfo': '일기 작성 정보',
      'branch': '가지',
      'home': '홈',
      'challenge': '도전과제',
      'friends': '친구',
      'shop': '상점',
      'buyItem': '구매하기',
      'writeDiary': '일기 작성하기',
      'wallpaper': '벽지',
      'background': '배경',
      'prop': '소품',
      'floor': '바닥',
      'character': '캐릭터',
      'emoticon': '이모티콘',
      'watchAdGetBranch': '광고 보고 가지 받기',
      'completed': '완료',
      'watch': '보기',
      'unowned': '미보유',
      'purchaseConfirm': '{item}을(를) 구매하시겠습니까?',
      'salePrice': 'SALE! {original} -> {discounted} 가지',
      'notEnoughBranch': '가지가 부족합니다.',
      'purchaseSuccess': '{item}을(를) 구매했습니다.',
      'decorate': '꾸미기',
      'owned': '보유중',
      'sale': 'SALE',
      'notifications': '알림',
      'markAllAsRead': '모두 읽음',
      'loadingNotifications': '알림을 불러오는 중이에요',
      'pleaseWait': '잠시만 기다려주세요',
      'errorLoadingNotifications': '알림을 불러오는 중 오류가 발생했습니다',
      'tryAgainLater': '잠시 후 다시 시도해주세요',
      'noNotifications': '알림이 없습니다',
      'noNotificationsDesc': '새로운 소식이 생기면 이곳에 알려드릴게요',
      'replyFrom': '{username}님의 답장',
      'cheerFrom': '{username}님의 응원',
      'wakeUpAlert': '깨우기 알림',
      'nestPokeAlert': '찌르기 알림',
      'friendRequest': '친구 요청',
      'accept': '수락',
      'reject': '거절',
      'replyCompleted': '답장 완료',
      'reply': '답장',
      'stickyNoteHint': '짧은 메시지를 남겨보세요',
      'decorateRoom': '방 꾸미기',
      'decorationSaved': '설정이 저장되었습니다! ✨',
      'saveFailed': '저장 실패: ',
      'save': '저장',
      'memo': '메모',
      'noProps': '구매한 소품이 없습니다. 상점에서 구매해 보세요!',
      'stickyNoteLimit': '메모는 하루에 한 번만 작성할 수 있습니다. ✍️',
      'noStickyNote': '보관 중인 메모 노트가 없습니다. 상점에서 구매해 주세요. 📦',
      'deleteStickyNote': '메모를 삭제하시겠습니까? 🗑️',
      'stickyNoteAdded': '메모가 추가되었습니다! (30가지 차감) 📝',
      'notEnoughPoints': '가지가 부족합니다. (30가지 필요)',
      // Main & Strings
      'greetingMorning': '좋은 아침이에요!',
      'greetingAfternoon': '좋은 오후예요!',
      'greetingEvening': '좋은 저녁이에요!',
      'consecutiveDays': '{days}일 연속 기록 중 🔥',
      'nicknameIntro': '반가워요! 사용하실 닉네임을 입력해주세요.',
      'start': '시작하기',
      'kakaoLogin': '카카오 로그인',
      'appleLogin': 'Apple 로그인',
      'nicknameChanged': '닉네임이 변경되었습니다! ✨',
      'errorSavingSettings': '설정 저장 중 오류가 발생했습니다: ',
      'enterNewNickname': '새 닉네임 입력',
      // Social
      'friendsTitle': '친구',
      'friendsCount': '{count}명',
      'addFriendEmpty': '친구를 추가해\n보세요',
      'newFriendRequests': '새로운 친구 요청',
      'friendRequestSent': '{nickname}님께\n친구 요청을 보냈습니다!',
      'youBecameFriends': '{nickname}님과 친구가 되었습니다!',
      'enterFriendNickname': '친구 닉네임 입력',
      'request': '요청',
      'invite': '초대하기',
      'userNotFound': '해당 닉네임의 사용자를 찾을 수 없습니다.',
      'selfRequestError': '자신에게는 친구 요청을 보낼 수 없습니다.',
      'addFriendButton': '+친구 추가',
      'friendRequestRejection': '친구 요청이 거절되었습니다.',
      'wakeUp': '깨우기',
      'written': '작성 완료',
      'wakeUpSuccess': '{nickname}님을 깨웠습니다! ⏰',
      'wakeUpFailed': '깨우기 요청 실패',
      'secondsUnit': '{seconds}초',
      // Challenge
      'challengesTitle': '도전과제',
      'challengesProgress': '도전과제 달성 수',
      'challengeCompleted': '도전과제 달성!',
      'challengeDetailCurrent': '현재',
      'challengeDetailTarget': '목표',
      'challengeDetailInfo': '도전과제 상세',
      'challengeDetailWarningTitle': '주의사항',
      'challengeDetailWarningDesc': '하루라도 빠지면 연속 기록이 0으로 초기화됩니다!',
      'challengeDetailCurrentRecord': '현재 기록',
      'challengeDetailRemaining': '같은 계열 남은 도전과제',
      'challengeDetailReward': '보상',
      'challengeDetailCurrentLabel': '현재',
      'challenge_dawn_start_title': '새벽의 시작',
      'challenge_dawn_start_desc': '오전 6시 이전에 일기 1회 작성하기',
      'challenge_steady_habit_title': '꾸준한 습관',
      'challenge_steady_habit_desc': '3일 연속 일기 작성하기',
      'challenge_morning_person_title': '진정한 아침형 인간',
      'challenge_morning_person_desc': '7일 연속 일기 작성하기',
      'challenge_rich_room_title': '풍성한 방',
      'challenge_rich_room_desc': '소품 3개 이상 구매하기',
      'challenge_social_king_title': '마당 넓은 주인',
      'challenge_social_king_desc': '친구 5명 맺기',
      'challenge_diary_master_title': '일기의 달인',
      'challenge_diary_master_desc': '누적 일기 30개 작성하기',
      'challenge_streak_14_title': '2주 연속 기록',
      'challenge_streak_14_desc': '14일 연속 일기 작성하기',
      'challenge_streak_21_title': '3주 연속 기록',
      'challenge_streak_21_desc': '21일 연속 일기 작성하기',
      'challenge_streak_30_title': '한 달의 기적',
      'challenge_streak_30_desc': '30일 연속 일기 작성하기',
      'challenge_friend_1_title': '첫 친구',
      'challenge_friend_1_desc': '첫 친구 만들기',
      'challenge_friend_10_title': '인기쟁이',
      'challenge_friend_10_desc': '친구 10명 만들기',
      'challenge_friend_20_title': '마당발',
      'challenge_friend_20_desc': '친구 20명 만들기',
      'challenge_prop_1_title': '첫 소품',
      'challenge_prop_1_desc': '소품 1개 구매하기',
      'challenge_prop_5_title': '꾸미기 꿈나무',
      'challenge_prop_5_desc': '소품 5개 구매하기',
      'challenge_prop_10_title': '맥시멀리스트',
      'challenge_prop_10_desc': '소품 10개 구매하기',
      'challenge_fashion_3_title': '패셔니스타',
      'challenge_fashion_3_desc': '캐릭터 아이템 3개 구매하기',
      'challenge_fashion_5_title': '트렌드세터',
      'challenge_fashion_5_desc': '캐릭터 아이템 5개 구매하기',
      'challenge_bg_1_title': '기분 전환',
      'challenge_bg_1_desc': '배경 1개 구매하기',
      'challenge_bg_3_title': '분위기 메이커',
      'challenge_bg_3_desc': '배경 3개 구매하기',
      'challenge_level_2_title': '첫 성장',
      'challenge_level_2_desc': '캐릭터 레벨 2 달성하기',
      'challenge_level_3_title': '쑥쑥 성장',
      'challenge_level_3_desc': '캐릭터 레벨 3 달성하기',
      'challenge_level_4_title': '거의 다 왔어',
      'challenge_level_4_desc': '캐릭터 레벨 4 달성하기',
      'challenge_level_5_title': '폭풍 성장',
      'challenge_level_5_desc': '캐릭터 레벨 5 달성하기',
      'challenge_memo_1_title': '첫 메모',
      'challenge_memo_1_desc': '첫 메모 작성하기',
      'challenge_memo_3_title': '메모 수집가',
      'challenge_memo_3_desc': '메모 3개 작성하기',
      'challenge_memo_10_title': '메모 매니아',
      'challenge_memo_10_desc': '메모 10개 작성하기',
      'challenge_memo_30_title': '메모 마스터',
      'challenge_memo_30_desc': '메모 30개 작성하기',
      'deleteAccountConfirmDesc': '정말로 탈퇴하시겠습니까?\n모든 데이터가 영구적으로 삭제됩니다.',
      'passwordConfirmHint': '비밀번호 확인',
      'deleteAccountConsent': '안내 사항을 모두 확인하였으며, 탈퇴에 동의합니다.',
      'noDiaryForDay': '이 날은 일기를 작성하지 않았습니다',
      'diaryRecordForDay': '{date} 기록',
      'biometricAuthReasonPastRecords': '과거 기록을 확인하기 위해 인증이 필요합니다',
      'biometricAuthFailed': '생체 인증에 실패했습니다. 🔒',
      'noMemos': '작성한 메모가 없습니다',
      'myMemos': '내 메모',
      'fullDateFormat': '{year}년 {month}월 {day}일 ({weekday})',
      'monthDayFormat': '{month}월 {day}일',
      'monthDayFormatWithWeekday': '{month}월 {day}일 ({weekday})',
      'state_egg': '알 🥚',
      'state_cracking': '금이 간 알 🥚✨',
      'state_hatching': '부화 중 🐣',
      'state_baby': '새끼 새 🐥',
      'state_young': '아기 새 🐦',
      'state_adult': '귀여운 새 🕊️',
      'state_sleeping': '수면 중 💤',
      'weekday_mon': '월',
      'weekday_tue': '화',
      'weekday_wed': '수',
      'weekday_thu': '목',
      'weekday_fri': '금',
      'weekday_sat': '토',
      'weekday_sun': '일',
      'noQuestion': '질문이 없습니다.',
      'previous': '이전',
      'next': '다음',
      'characterInfo': '캐릭터 정보',
      // AppDialog
      'biometricErrorTitle': '생체 인증 실패',
      'biometricErrorDesc': '생체 인증에 실패했습니다. 다시 시도하거나 로그아웃할 수 있습니다.',
      'logoutTitle': '로그아웃',
      'logoutDesc': '정말 로그아웃 하시겠습니까?',
      'deleteAccountTitle': '회원탈퇴',
      'deleteAccountDesc': '정말 회원탈퇴 하시겠습니까?\n모든 데이터가 삭제되며 복구할 수 없습니다.',
      'addFriendTitle': '친구 추가',
      'cheerMessageTitle': '응원 메시지',
      'exitWritingTitle': '작성을 중단하시겠어요?',
      'sentMessagesTitle': '보낸 메시지',
      'purchaseTitle': '아이템 구매',
      'purchaseCompleteTitle': '구매 완료',
      'levelUpTitle': '🎊 축하합니다! 🎊',
      'levelUpDesc': '캐릭터가 새로운 단계로 성장했어요!',
      'continueGrowth': '앞으로도 꾸준히 성장을 도와주세요.',
      'maxLevel': '최대 레벨',
      'adRewardTitle': '가지 획득!',
      'adRewardDesc': '광고 시청 보상으로\n10 가지를 획득했습니다!',
      'deleteFriendTitle': '친구 삭제',
      'deleteFriendDesc': '친구를 삭제하시겠습니까?',
      'reportTitle': '신고하기',
      'report': '신고',
      'ok': '확인',
      'close': '닫기',
      // Items (Names)
      'item_name_default': '기본',
      'item_name_stripe': '스트라이프',
      'item_name_check': '체크',
      'item_name_dot': '도트',
      'item_name_flower_sky': '꽃하늘',
      'item_name_pink_lace': '핑크레이스',
      'item_name_red_heart': '빨간하트',
      'item_name_colorful_hexagon': '컬러풀육각형',
      'item_name_Space_Background': '우주',
      'item_name_Castle_Stone_Wall': '중세 성 벽지',
      'item_name_lego_wallpaper': '블럭 벽지',
      'item_name_DarkPanel': '다크 패널',
      'item_name_IvoryClassic': '아이보리 클래식',
      'item_name_light': '라이트',
      'item_name_happy': '행복',
      'item_name_normal': '평범',
      'item_name_sad': '슬픔',
      'item_name_love': '사랑',
      'item_name_angry': '화남',
      'item_name_awkward': '당황',
      'item_name_move': '감동',
      'item_name_sleep': '졸림',
      'item_name_blue_moon': '푸른 달',
      'item_name_blue_moon2': '푸른 달2',
      'item_name_golden_sun': '황금 태양',
      'item_name_starry_night': '별이 빛나는 밤',
      'item_name_alarm_clock': '알람시계',
      'item_name_wood_desk': '원목 책상',
      'item_name_book_desk': '독서대',
      'item_name_wooden_desk_sprite': '원목 책상2',
      'item_name_space_desk': '우주 책상',
      'item_name_space_desk2': '우주 책상2',
      'item_name_space_drawer': '우주 서랍장',
      'item_name_space_drawer2': '우주 서랍장2',
      'item_name_wood_chair': '원목 의자',
      'item_name_wood_bed': '원목 침대',
      'item_name_space_chair': '우주 의자',
      'item_name_space_bed': '우주 침대',
      'item_name_pogeun_sofa': '포근소파',
      'item_name_cozy_bean': '낮잠소파',
      'item_name_pot_1': '식물 화분',
      'item_name_analog_clock': '아날로그 시계',
      'item_name_white_bear': '흰 곰 인형',
      'item_name_pink_chair': '핑크 의자',
      'item_name_blue_chair': '파란 의자',
      'item_name_mug_cup': '머그컵',
      'item_name_wood_cup': '원목 컵',
      'item_name_cloud_watch': '구름 시계',
      'item_name_red_carpet': '레드 카펫',
      'item_name_sticky_note': '메모',
      'item_name_wood': '나무 바닥',
      'item_name_wood2': '나무 바닥2',
      'item_name_pink_wood': '핑크 나무 바닥',
      'item_name_peach_break': '피치피치',
      'item_name_pink_carpet': '핑크 카펫',
      'item_name_alokdalok': '알록달록',
      'item_name_castle_stone': '중세 성 바닥',
      'item_name_space_floor': '우주 바닥',
      'item_name_lego_book_desk': '블럭 독서 책상',
      'item_name_lego_chair': '블럭 의자',
      'item_name_lego_clock': '블럭 시계',
      'item_name_lego_cloth_desk': '블럭 천 책상',
      'item_name_lego_desk': '블럭 책상',
      'item_name_lego_door': '블럭 문',
      'item_name_lego_flower': '블럭 꽃',
      'item_name_lego_frame': '블럭 액자',
      'item_name_lego_frame2': '블럭 액자2',
      'item_name_lego_game_machine': '블럭 게임기',
      'item_name_lego_lamp': '블럭 램프',
      'item_name_lego_mailbox': '블럭 우체통',
      'item_name_lego_piano': '블럭 피아노',
      'item_name_lego_sink': '블럭 세면대',
      'item_name_lego_floor': '블럭 바닥',
      'item_name_DarkWood_Floor': '어두운 나무 바닥',
      'item_name_lego_lug': '블럭 러그',
      'item_name_wall_lamp': '벽조명',
      'item_name_warm_lamp': '따뜻한 램프',
      // Login & Auth
      'login': '로그인',
      'signup': '회원가입',
      'emailPlaceholder': '이메일',
      'passwordPlaceholder': '비밀번호',
      'loginWithGoogle': 'Google로 계속하기',
      'loginWithKakao': '카카오로 계속하기',
      'loginWithApple': 'Apple로 계속하기',
      'loginWithID': 'ID로 로그인',
      'idLogin': 'ID 로그인',
      'noAccountSignup': '계정이 없으신가요? 회원가입',
      'alreadyHaveAccountLogin': '계정이 있으신가요? 로그인',
      'emailRequired': '이메일을 입력해주세요',
      'emailInvalid': '올바른 이메일 형식이 아닙니다',
      'passwordRequired': '비밀번호를 입력해주세요',
      'passwordLengthError': '비밀번호는 최소 6자 이상이어야 합니다',
      'namePlaceholder': '이름',
      'nameRequired': '이름을 입력해주세요',
      'passwordConfirmPlaceholder': '비밀번호 확인',
      'passwordMismatch': '비밀번호가 일치하지 않습니다',
      'signupSuccess': '회원가입이 완료되었습니다! 로그인해주세요.',
      'loginError': '로그인 실패',
      'signupError': '회원가입 실패',
      'introTitle': 'Morni',
      'introSubtitle': '아침을 함께하는 당신의 메이트',
      // Notification Settings
      'serviceNotification': '서비스 알림',
      'morningDiaryNoti': '아침 일기 알림',
      'morningDiaryNotiDesc': '아침마다 일기 작성을 잊지 않도록 알려드려요',
      'activityNotification': '활동 알림',
      'wakeUpNoti': '깨우기 알림',
      'wakeUpNotiDesc': '친구가 나를 깨웠을 때 알림을 받아요',
      'cheerMessageNoti': '응원 메시지 알림',
      'cheerMessageNotiDesc': '친구가 응원 메시지를 남겼을 때 알림을 받아요',
      'friendNotification': '친구 알림',
      'friendRequestNoti': '친구 요청 알림',
      'friendRequestNotiDesc': '새로운 친구 요청이 오면 알려드려요',
      'friendAcceptNoti': '친구 수락 알림',
      'friendAcceptNotiDesc': '상대방이 내 친구 요청을 수락하면 알려드려요',
      'friendRejectNoti': '친구 거절 알림',
      'friendRejectNotiDesc': '내 친구 요청이 거절되었을 때 알림을 받아요',
      'notificationTime': '알림 시간 설정',
      'timePickerHour': '시',
      'timePickerMinute': '분',
      'nestNotification': '둥지 알림',
      'nestInviteNoti': '둥지 초대 알림',
      'nestInviteNotiDesc': '둥지 초대를 받았을 때 알림을 받아요',
      'nestDonationNoti': '가지 기부 알림',
      'nestDonationNotiDesc': '둥지 멤버가 가지를 기부했을 때 알림을 받아요',
      // Writing Screen
      'tempSave': '임시저장',
      'saveDraft': '임시저장',
      'saveDraftSuccess': '임시 저장되었습니다. 📝',
      'saveDraftError': '임시 저장 중 오류가 발생했습니다. ⚠️',
      'saveDiarySuccess': '저장되었습니다! 캐릭터가 깨어났어요! ☀️',
      'saveDiaryError': '저장 중 오류가 발생했습니다. ⚠️',
      'diaryCompletionTitle': '캐릭터가 깨어났어요!',
      'diaryCompletionDesc': '캐릭터가 하루를 시작했어요!',
      'branchEarned': '+{amount} 가지 획득',
      'exitConfirmation': '작성을 중단하시겠어요?',
      'exitConfirmationDesc': '작성 중인 내용은 저장되지 않습니다.',
      'keepWriting': '계속 작성',
      'stop': '중단',
      'writingHint': '지금 머릿속에 떠오르는 생각을 자유롭게 적어보세요.',
      'todayQuestion': '오늘의 질문',
      'moreWriting': '조금만 더 작성해주세요! ✍️',
      'authRequiredForSave': '일기를 안전하게 저장하기 위해 인증이 필요합니다',
      'authFailedForSave': '인증에 실패하여 일기를 저장할 수 없습니다. 🔒',
      // Archive & Diary Detail
      'diaryContent': '일기 내용',
      'encryptedDiary': '암호화된 일기',
      'diaryLoadError': '일기 내용을 불러오는데 실패했습니다.',
      'noDiaryContent': '일기 내용이 없습니다.',
      'emotionalAnalysis': '감정 분석',
      'totalDiaries': '총 일기',
      'consecutiveDaysLabel': '연속 작성',
      'days': '일',
      // Common
      'edit': '수정',
      'yes': '네',
      'no': '아니오',
      'equipped': '장착됨',
      'stampEquipped': '장착',
      'unequipped': '장착해제',
      'item_name_heart_glass': '하트 안경',
      'item_name_blue_ribbon': '파란 리본',
      'item_name_pink_mupler': '분홍 목도리',
      'item_name_necktie': '넥타이',
      'item_name_plogeyes': '개구리 눈',
      'item_name_sprout': '새싹',
      'item_name_crown': '왕관',
      'item_name_wood_glass': '나무 안경',
      'item_name_space_clothes': '우주복',
      'item_name_prog_clothes': '개굴옷',
      'item_name_superb_bird_clothes': '극락조 새옷',
      'item_name_humming_bird_clothes': '벌새옷',
      'item_name_knight_helm': '기사 투구',
      'item_name_castle_candle': '성 촛대',
      'item_name_castle_knight_statue': '기사 조각상',
      'item_name_castle_treasure_chest': '보물 상자',
      'item_name_castle_gargoyle_statue': '가고일 석상',
      'decorateCharacter': '캐릭터 꾸미기',
      'unequipAll': '모두 해제',
      'removeAllProps': '모두 제거',
      'showOwnedOnly': '보유중인 상품만 보기',
      'bulkPurchase': '일괄구매',
      'bulkPurchaseConfirm': '구매하지 않은 상품이 있습니다.\n일괄 구매하시겠습니까?',
      'totalPrice': '총 합계: ',
      'purchaseAndSaveSuccess': '구매 및 저장이 완료되었습니다! ✨',
      'all': '전체',
      'head': '머리',
      'face': '얼굴',
      'clothes': '옷',
      'accessory': '장식',
      'viewDiaryContent': '일기 내용 보기',
      'suspensionTitle': '이용 제한 안내',
      'unsuspendTitle': '정지 해제',
      'suspensionContent': '커뮤니티 가이드라인 위반으로 인해\n서비스 이용이 일시적으로 제한되었습니다.',
      'remainingTimeTitle': '해제까지 남은 시간',
      'permanentSuspension': '영구 정지',
      'daysRemaining': '{days}일 {hours}시간 남음',
      'hoursRemaining': '{hours}시간 {minutes}분 남음',
      'minutesRemaining': '{minutes}분 남음',
      'suspensionReason': '사유: {reason}',
      'reason_community_violation': '커뮤니티 가이드라인 위반',
      // Friend Room
      'sendCheerMessage': '응원메시지 보내기',
      'resendAfterSeconds': '{seconds}초 후 재전송',
      'sentHistory': '보낸기록',
      'friend': '친구',
      'cheerMessageHint': '친구에게 응원의 메시지를 남겨주세요',
      'cheerMessageSent': '응원 메시지를 보냈습니다! 💌',
      'cheerMessageSendFailed': '응원 메시지 전송에 실패했습니다.',
      'leave': '남기기',
      'noSentMessages': '아직 보낸 메시지가 없어요',
      'userReport': '사용자 신고',
      'reportReasonSelect': '신고 사유를 선택해주세요.',
      'reportSubmitted': '신고가 접수되었습니다.',
      'reportError': '신고 접수 중 오류가 발생했습니다.',
      'reportReasonInappropriate': '부적절한 내용',
      'reportReasonAbusive': '욕설/비하 발언',
      'reportReasonSpam': '스팸/광고',
      'reportReasonOther': '기타',
      'deleteFriendConfirm': '{nickname}님을 친구 목록에서\n삭제하시겠습니까?',
      'delete': '삭제',
      'friendDeleted': '친구가 삭제되었습니다.',
      'friendDeleteError': '친구 삭제 중 오류가 발생했습니다.',
      // Nest Room
      'nest': '둥지',
      'nestList': '둥지 목록',
      'participatingNests': '참여 중인 둥지',
      'myNests': '내가 만든 둥지',
      'createNest': '+ 둥지 만들기',
      'nestLevel': 'Lv.{level}',
      'nestPeopleCount': '{current}/{max}',
      'createdAt': '생성일',
      'lastActivity': '{time} 전 활동',
      'todayActivity': '오늘 활동',
      'yesterdayActivity': '어제 활동',
      'hoursAgo': '{hours}시간',
      'minutesAgo': '{minutes}분',
      'justNow': '방금',
      'recentActivity': '최근 활동',
      'createNestTitle': '둥지 만들기',
      'nestName': '둥지 이름',
      'enterNestName': '둥지 이름을 입력하세요',
      'maxPeople': '최대 인원',
      'isPublic': '공개 설정',
      'public': '공개',
      'private': '비공개',
      'create': '만들기',
      'unknown': '알 수 없음',
      'nestEditTitle': '둥지 수정',
      'collectGajiTitle': '가지 모으기',
      'nestInvitePopupTitle': '둥지 초대',
      'nestCreateTitle': '둥지 만들기',
      'nestNoParticipating': '참여중인 둥지가 없어요',
      'nestNoMyNests': '내가 만든 둥지가 없어요',
      'nestCreateNew': '새로운 둥지를 만들어 보세요!',
      'nestInviteButton': '+ 둥지 초대',
      'nestPlaceholderDesc': '우리의 둥지 이야기',
      'nestActivityJustNow': '방금 전 활동',
      'nestActivityDaysAgo': '{days}일 전 활동',
      'nestActivityHoursAgo': '{hours}시간 전 활동',
      'nestActivityMinutesAgo': '{minutes}분 전 활동',
      'nestEnter': '입장하기 >',
      'nestInvite': '둥지 초대',
      'nestDonation': '둥지 기부',
      'nestInviteTitle': '새로운 둥지 초대',
      'nestLabel': '둥지: {name}',
      'nestInvitePlaceholder': '초대할 친구의 닉네임을 입력하세요',
      'nestSelfInviteError': '자신을 초대할 수 없습니다.',
      'nestUserNotFoundError': '존재하지 않는 닉네임입니다.',
      'nestAlreadyMemberError': '이미 둥지에 있는 사용자입니다.',
      'nestInviteSent': '{nickname}님에게 초대 요청을 보냈습니다.',
      'nestInviteFailed': '초대 실패: {error}',
      'nestCollectHint': '모을 수량을 입력하세요',
      'nestCollectButton': '모으기',
      'nestInvalidAmount': '올바른 숫자를 입력해주세요.',
      'nestNotEnoughGaji': '보유한 가지보다 많이 모을 수 없습니다.',
      'nestCollectSuccessTitle': '모으기 완료',
      'nestCollectSuccessDesc': '가지 {amount}개 모으기 성공!',
      'nestManageTitle': '둥지 관리',
      'nestNameHint': '둥지 이름을 입력하세요',
      'nestDescHint': '둥지 설명을 입력하세요 (최대 15자)',
      'nestUpdateSuccess': '둥지 정보를 수정했습니다!',
      'nestCreateSuccess': '둥지가 생성되었습니다! ✨',
      'nestMyStreak': '나의 연속 기록: {days}일!',
      'nestPokeCooldown': '앗! {seconds}초 뒤에 다시 찌를 수 있어요!',
      'nestPokeSuccess': '{nickname}님을 찔렀어요!',
      'nestPokeDescription': '{nickname}: 연속 {days}일! (더블탭해서 찌르기)',
      'nestNoMembers': '아직 멤버가 없습니다.',
      'errorOccurred': '오류가 발생했습니다.',
      'dayUnit': '일',
      'nestMaxCountError': '최대 2개의 둥지만 만들 수 있습니다.',
      'nestInvalidDonateAmount': '기부할 가지의 수를 정확히 입력해주세요.',
      'nestNotEnoughGajiError': '보유하고 있는 가지가 부족합니다.',
      'nestEmptyMessageError': '한마디를 입력해주세요.',
      'nestEmptyNameError': '둥지 이름을 입력해주세요.',
      'nestFullTitle': '둥지 정원 초과',
      'nestFullError': '10명이 꽉차서 더 이상 입장할 수 없습니다.',
      'nestLeaveConfirm': '\'{name}\' 둥지에서 정말 나가시겠습니까?',
      'nestDeleteConfirm':
          '\'{name}\' 둥지를 정말 삭제하시겠습니까?\n모든 멤버가 탈퇴 처리되며 복구할 수 없습니다.',
      'nestLeaveTitle': '둥지 나가기',
      'nestDeleteTitle': '둥지 삭제',
      'nestDeleteSuccess': '둥지가 삭제되었습니다.',
      'nestLeaveSuccess': '둥지에서 퇴장했습니다.',
      'nestWithdraw': '나가기',
      'nestUpgradeTitle': '둥지 업그레이드',
      'nestUpgradeConfirm': '둥지를 레벨 2로 업그레이드 하시겠습니까?\n배경이 바뀌고 정원이 15명으로 늘어납니다.',
      'nestUpgradeSuccess': '둥지가 레벨 2로 업그레이드 되었습니다!',
      'nestUpgrade': '업그레이드',
      'upgrade': '업그레이드',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String getFormat(String key, Map<String, String> args) {
    String text = get(key);
    args.forEach((k, v) {
      text = text.replaceAll('{$k}', v);
    });
    return text;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ko'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
