import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  String get mainFontFamily =>
      locale.languageCode == 'ja' ? 'KiwiMaru' : 'BMJUA';
  String get handwritingFontFamily =>
      locale.languageCode == 'ja' ? 'KiwiMaru' : 'KyoboHandwriting2024psw';

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'account': 'Account',
      'changeNickname': 'Change Nickname',
      'email': 'Email',
      'security': 'Security',
      'biometricAuth': 'Biometric Auth',
      'biometricAuthDescEnabled': 'Biometric auth required',
      'biometricAuthDescDisabled': 'Protect app with biometric auth',
      'changePassword': 'Change Password',
      'appSettings': 'App Settings',
      'writingBlur': 'Writing Blur Default',
      'writingBlurDescEnabled': 'Blur writing by default',
      'writingBlurDescDisabled': 'Show writing by default',
      'notificationSettings': 'Notification Settings',
      'language': 'Language',
      'info': 'Info',
      'versionInfo': 'Version Info',
      'termsOfService': 'Service Terms',
      'privacyPolicy': 'Privacy Policy',
      'termsAndPrivacy': 'Terms & Privacy',
      'faq': 'FAQ',
      'support': 'Contact Us',
      'logout': 'Logout',
      'deleteAccount': 'Delete Account',
      'nicknamePlaceholder': 'Enter nickname (2-15 chars)',
      'cancel': 'Cancel',
      'change': 'Change',
      'confirm': 'Confirm',
      'retry': 'Retry',
      'update': 'Update',
      'later': 'Later',
      'updateNotice': 'Update Notice',
      'error': 'Error',
      'nicknameLengthError': 'Nickname must be at least 2 characters',
      'nicknameTakenError': 'Nickname is already taken',
      'korean': 'Korean',
      'english': 'English',
      'japanese': 'Japanese',
      'selectLanguage': 'Select Language',
      'collectMyMemos': 'Collect My Memos',
      'myPage': 'Record',
      'diaryWritingInfo': 'Diary Writing Info',
      'branch': 'Branch',
      'home': 'Home',
      'challenge': 'Challenge',
      'friends': 'Friends',
      'shop': 'Shop',
      'buyItem': 'Purchase',
      'todayShop': "Today's Shop",
      'allItems': 'All Items',
      'newItems': 'New',
      'writeDiary': 'Write Diary',
      'wallpaper': 'Wallpaper',
      'background': 'Background',
      'prop': 'Prop',
      'floor': 'Floor',
      'character': 'Character',
      'emoticon': 'Emoticon',
      'watchAdGetBranch': 'Watch Ad Get 20 Branches',
      'completed': 'Diary Completed',
      'watch': 'Watch',
      'unowned': 'Unowned',
      'purchaseConfirm': 'Do you want to purchase {item}?',
      'salePrice': 'SALE! {original} -> {discounted} Branch',
      'notEnoughBranch': 'Not enough branches.',
      'purchaseSuccess': '{item} purchased.',
      'decorate': 'Decorate',
      'owned': 'Owned',
      'sale': 'SALE',
      'notifications': 'Notifications',
      'markAllAsRead': 'Mark all as read',
      'loadingNotifications': 'Loading notifications...',
      'pleaseWait': 'Please wait',
      'errorLoadingNotifications': 'Error loading notifications',
      'tryAgainLater': 'Please try again later',
      'noNotifications': 'No notifications',
      'noNotificationsDesc': 'We will notify you when there is news',
      'replyFrom': 'Reply from {username}',
      'cheerFrom': 'Cheer from {username}',
      'wakeUpAlert': 'Wake up alert',
      'nestPokeAlert': 'Nest Poke',
      'friendRequest': 'Friend Request',
      'accept': 'Accept',
      'reject': 'Reject',
      'replyCompleted': 'Replied',
      'reply': 'Reply',
      'free': 'Free',
      'ad': 'Ad',
      'skip': 'Skip',
      'stickyNoteHint': 'Leave a short message',
      'decorateRoom': 'Decorate Room',
      'decorationSaved': 'Settings saved! ✨',
      'pointHistoryTitle': 'Branch Transaction History',
      'noPointHistory': 'No branch history yet.',
      'historyPurchaseTheme': 'Theme Purchase',
      'historyPurchaseBackground': 'Background Purchase',
      'historyPurchaseWallpaper': 'Wallpaper Purchase',
      'historyPurchaseProp': 'Prop Purchase',
      'historyPurchaseEmoticon': 'Emoticon Purchase',
      'historyPurchaseFloor': 'Floor Purchase',
      'historyPurchaseWindow': 'Window Purchase',
      'historyPurchaseCharacterItem': 'Item Purchase',
      'historyDiaryReward': 'Diary Reward',
      'historyAdReward': 'Ad Reward',
      'historyChallengeReward': 'Challenge Completed',
      'historyDonation': 'Nest Donation',
      'historyNestReward': 'Nest Word Reward',
      'historyShopTutorialReward': 'Shop Tutorial Completion Reward',
      'historyStickyNote': 'Write Memo',
      'unownedItemsWarning':
          'Some placed items are not owned yet!\nUnowned items can be obtained from the shop.\nSave without them?',
      'saveFailed': 'Save failed: ',
      'save': 'Save',
      'noProps': 'You don\'t have any props. Buy some in the shop!',
      'stickyNoteLimit': 'You can only write a note once a day. ✍️',
      'noStickyNote':
          'You don\'t have a sticky note. Please buy one from the shop. 📦',
      'deleteStickyNote': 'Do you want to delete this memo? 🗑️',
      'stickyNoteAdded': 'Memo added! (5 branches deducted) 📝',
      'notEnoughPoints': 'Not enough branches! (5 required)',
      'myReferralCode': 'My Referral Code',
      'referralCodeCopied': 'Referral code copied.',
      // Main & Strings
      'greetingMorning': 'Good morning!',
      'greetingAfternoon': 'Good afternoon!',
      'greetingEvening': 'Good evening!',
      'consecutiveDays': '{days} days consecutive streak 🔥',
      'nicknameIntro': 'Nice to meet you! Please enter your nickname.',
      'start': 'Start',
      'kakaoLogin': 'Kakao Login',
      'appleLogin': 'Apple Login',
      'nicknameChanged': 'Nickname changed! ✨',
      'errorSavingSettings': 'Error saving settings: ',
      'enterNewNickname': 'Enter new nickname',
      // Social
      'friendsTitle': 'Friends',
      'friendsCount': '{count}',
      'addFriendEmpty': 'Add a friend',
      'newFriendRequests': 'New friend requests',
      'friendRequestSent': 'Friend request sent to {nickname}!',
      'youBecameFriends': 'You became friends with {nickname}!',
      'enterFriendNickname': 'Enter friend nickname',
      'request': 'Request',
      'invite': 'Invite',
      'userNotFound': 'User not found.',
      'selfRequestError': 'You cannot send a request to yourself.',
      'addFriendButton': '+ Add Friend',
      'friendRequestRejection': 'Friend request rejected.',
      'wakeUp': 'Wake Up',
      'written': 'Written',
      'wakeUpSuccess': 'You woke up {nickname}! ⏰',
      'wakeUpFailed': 'Failed to wake up friend.',
      'secondsUnit': '{seconds}s',
      // Challenge
      'challengesTitle': 'Challenges',
      'challengesProgress': 'Challenges Completed',
      'challengeCompleted': 'Challenge Completed!',
      'challengeDetailCurrent': 'Current',
      'challengeDetailTarget': 'Target',
      'challengeDetailInfo': 'Challenge Details',
      'challengeDetailWarningTitle': 'Caution',
      'challengeDetailWarningDesc':
          'If you miss even one day, the consecutive record resets to 0!',
      'challengeDetailCurrentRecord': 'Current Record',
      'challengeDetailRemaining': 'Remaining in this series',
      'challengeDetailReward': 'Reward',
      'challengeDetailCurrentLabel': 'Current',
      'challenge_dawn_start_title': 'Start of Dawn',
      'challenge_dawn_start_desc': 'Write a diary before 6 AM once',
      'challenge_steady_habit_title': 'Steady Habit',
      'challenge_steady_habit_desc': 'Write diary for 3 consecutive days',
      'challenge_morning_person_title': 'True Morning Person',
      'challenge_morning_person_desc': 'Write diary for 7 consecutive days',
      'challenge_rich_room_title': 'Rich Room',
      'challenge_rich_room_desc': 'Buy 3 or more props',
      'challenge_social_king_title': 'Social King',
      'challenge_social_king_desc': 'Make 5 friends',
      'challenge_diary_master_title': 'Diary Master',
      'challenge_diary_master_desc': 'Write 30 diaries in total',
      'challenge_streak_14_title': '2 Weeks Streak',
      'challenge_streak_14_desc': 'Write diary for 14 consecutive days',
      'challenge_streak_21_title': '3 Weeks Streak',
      'challenge_streak_21_desc': 'Write diary for 21 consecutive days',
      'challenge_streak_30_title': 'Monthly Master',
      'challenge_streak_30_desc': 'Write diary for 30 consecutive days',
      'challenge_friend_1_title': 'First Friend',
      'challenge_friend_1_desc': 'Make your first friend',
      'challenge_friend_10_title': 'Popular',
      'challenge_friend_10_desc': 'Make 10 friends',
      'challenge_friend_20_title': 'Social Celebrity',
      'challenge_friend_20_desc': 'Make 20 friends',
      'challenge_prop_1_title': 'First Decoration',
      'challenge_prop_1_desc': 'Buy 1 prop',
      'challenge_prop_5_title': 'Decorator',
      'challenge_prop_5_desc': 'Buy 5 props',
      'challenge_prop_10_title': 'Maximalist',
      'challenge_prop_10_desc': 'Buy 10 props',
      'challenge_fashion_3_title': 'Fashionista',
      'challenge_fashion_3_desc': 'Buy 3 character items',
      'challenge_fashion_5_title': 'Trendsetter',
      'challenge_fashion_5_desc': 'Buy 5 character items',
      'challenge_bg_1_title': 'Mood Change',
      'challenge_bg_1_desc': 'Buy 1 background',
      'challenge_bg_3_title': 'Atmosphere Master',
      'challenge_bg_3_desc': 'Buy 3 backgrounds',
      'challenge_level_2_title': 'First Growth',
      'challenge_level_2_desc': 'Reach Character Level 2',
      'challenge_level_3_title': 'Growing Up',
      'challenge_level_3_desc': 'Reach Character Level 3',
      'challenge_level_4_title': 'Almost There',
      'challenge_level_4_desc': 'Reach Character Level 4',
      'challenge_level_5_title': 'Fully Grown',
      'challenge_level_5_desc': 'Reach Character Level 5',
      'challenge_memo_1_title': 'First Memo',
      'challenge_memo_1_desc': 'Write your first memo',
      'challenge_memo_3_title': 'Memo Collector',
      'challenge_memo_3_desc': 'Write 3 memos',
      'challenge_memo_10_title': 'Memo Maniac',
      'challenge_memo_10_desc': 'Write 10 memos',
      'challenge_memo_30_title': 'Memo Master',
      'challenge_memo_30_desc': 'Write 30 memos',
      'deleteAccountConfirmDesc':
          'Are you sure you want to delete your account?\nAll data will be permanently deleted.',
      'passwordConfirmHint': 'Verify Password',
      'deleteAccountConsent':
          'I have read the notices and agree to delete my account.',
      'noDiaryForDay': 'No diary recorded for this day',
      'diaryRecordForDay': '{date} Record',
      'biometricAuthReasonPastRecords':
          'Authentication required to view past records',
      'biometricAuthFailed': 'Biometric authentication failed. 🔒',
      'noMemos': 'No memos written',
      'myMemos': 'My Memos',
      'fullDateFormat': '{year}.{month}.{day} ({weekday})',
      'monthDayFormat': '{month}.{day}',
      'monthDayFormatWithWeekday': '{month}.{day} ({weekday})',
      'state_egg': 'Egg 🥚',
      'state_cracking': 'Cracking Egg 🥚✨',
      'state_hatching': 'Hatching 🐣',
      'state_baby': 'Baby Bird 🐥',
      'state_young': 'Young Bird 🐦',
      'state_adult': 'Cute Bird 🕊️',
      'state_sleeping': 'Sleeping 💤',
      'weekday_mon': 'Mon',
      'weekday_tue': 'Tue',
      'weekday_wed': 'Wed',
      'weekday_thu': 'Thu',
      'weekday_fri': 'Fri',
      'weekday_sat': 'Sat',
      'weekday_sun': 'Sun',
      'noQuestion': 'No question.',
      'previous': 'Previous',
      'next': 'Next',
      'gift_popup_title': 'Special Gift 🎁',
      'gift_popup_welcome': 'Welcome on your first visit! 🎉',
      'gift_popup_desc': 'A special gift has arrived.',
      'receive': 'Receive',
      'characterInfo': 'Character Info',
      // AppDialog
      'biometricErrorTitle': 'Biometric Auth Failed',
      'biometricErrorDesc':
          'Biometric authentication failed. Please try again or logout.',
      'logoutTitle': 'Logout',
      'logoutDesc': 'Are you sure you want to logout?',
      'deleteAccountTitle': 'Delete Account',
      'deleteAccountDesc':
          'Are you sure you want to delete your account?\nAll data will be deleted and cannot be recovered.',
      'pageNotFound': 'Page not found',
      'addFriendTitle': 'Add Friend',
      'cheerMessageTitle': 'Cheer Message',
      'exitWritingTitle': 'Stop Writing?',
      'exitWritingDesc':
          'If you stop now, your progress will not be saved. (Try using Draft!)',
      'keepWriting': 'Keep Writing',
      'stop': 'Stop',
      'sentMessagesTitle': 'Sent Messages',
      'purchaseTitle': 'Purchase Item',
      'purchaseCompleteTitle': 'Purchase Complete',
      'levelUpTitle': '🎊 Congratulations! 🎊',
      'levelUpDesc': 'Your character has grown to a new level!',
      'continueGrowth': 'Please continue to help them grow.',
      'maxLevel': 'Max Level',
      'adRewardTitle': 'Branch Earned!',
      'adRewardDesc': 'You earned 20 branches for watching the ad!',
      'deleteFriendTitle': 'Delete Friend',
      'deleteFriendDesc': 'Are you sure you want to delete this friend?',
      'reportTitle': 'Report',
      'report': 'Report',
      'ok': 'OK',
      'close': 'Close',
      'bonusAdOfferTitle': '🎁 Bonus Branch!',
      'bonusAdOfferDesc': 'Watch an ad and get 20 bonus branches!',
      'bonusAdOfferWarning':
          'Warning: Closing the ad before it finishes will not grant the reward.',
      'watchAd': 'Watch Ad',
      // Items (Names)
      'item_name_default': 'Basic',
      'item_name_stripe': 'Stripe',
      'item_name_check': 'Check',
      'item_name_dot': 'Dot',
      'item_name_flower_sky': 'Flower Sky',
      'item_name_pink_lace': 'Pink Lace',
      'item_name_red_heart': 'Red Heart',
      'item_name_colorful_hexagon': 'Colorful Hexagon',
      'item_name_Space_Background': 'Space',
      'item_name_Castle_Stone_Wall': 'Medieval Castle Wall',
      'item_name_lego_wallpaper': 'Block Wallpaper',
      'item_name_DarkPanel': 'Dark Panel',
      'item_name_IvoryClassic': 'Ivory Classic',
      'item_name_light': 'Light',
      'item_name_happy': 'Happy',
      'item_name_normal': 'Normal',
      'item_name_sad': 'Sad',
      'item_name_love': 'Love',
      'item_name_angry': 'Angry',
      'item_name_awkward': 'Awkward',
      'item_name_move': 'Touched',
      'item_name_sleep': 'Sleepy',
      'item_name_blue_moon': 'Blue Moon',
      'item_name_blue_moon2': 'Blue Moon 2',
      'item_name_golden_sun': 'Golden Sun',
      'item_name_starry_night': 'Starry Night',
      'item_name_alarm_clock': 'Alarm Clock',
      'item_name_wood_desk': 'Wood Desk',
      'item_name_book_desk': 'Reading Desk',
      'item_name_wooden_desk_sprite': 'Wood Desk 2',
      'item_name_space_desk': 'Space Desk',
      'item_name_space_desk2': 'Space Desk 2',
      'item_name_space_drawer': 'Space Drawer',
      'item_name_space_drawer2': 'Space Drawer 2',
      'item_name_wood_chair': 'Wood Chair',
      'item_name_wood_bed': 'Wood Bed',
      'item_name_space_chair': 'Space Chair',
      'item_name_space_bed': 'Space Bed',
      'item_name_pogeun_sofa': 'Cozy Sofa',
      'item_name_cozy_bean': 'Nap Sofa',
      'item_name_pot_1': 'Plant Pot',
      'item_name_analog_clock': 'Analog Clock',
      'item_name_white_bear': 'White Bear',
      'item_name_pink_chair': 'Pink Chair',
      'item_name_blue_chair': 'Blue Chair',
      'item_name_mug_cup': 'Mug Cup',
      'item_name_wood_cup': 'Wood Cup',
      'item_name_cloud_watch': 'Cloud Clock',
      'item_name_red_carpet': 'Red Carpet',
      'item_name_sticky_note': 'Memo Note',
      'item_name_wood': 'Wood Floor',
      'item_name_wood2': 'Wood Floor 2',
      'item_name_pink_wood': 'Pink Wood Floor',
      'item_name_peach_break': 'Peach Pitch',
      'item_name_pink_carpet': 'Pink Carpet',
      'item_name_alokdalok': 'Colorful',
      'item_name_castle_stone': 'Medieval Stone Floor',
      'item_name_space_floor': 'Space Floor',
      'item_name_lego_book_desk': 'Block Book Desk',
      'item_name_lego_chair': 'Block Chair',
      'item_name_lego_clock': 'Block Clock',
      'item_name_lego_cloth_desk': 'Block Cloth Desk',
      'item_name_lego_desk': 'Block Desk',
      'item_name_lego_door': 'Block Door',
      'item_name_lego_flower': 'Block Flower',
      'item_name_lego_frame': 'Block Frame',
      'item_name_lego_frame2': 'Block Frame 2',
      'item_name_lego_game_machine': 'Block Game Machine',
      'item_name_lego_lamp': 'Block Lamp',
      'item_name_lego_mailbox': 'Block Mailbox',
      'item_name_lego_piano': 'Block Piano',
      'item_name_lego_sink': 'Block Sink',
      'item_name_lego_floor': 'Block Floor',
      'item_name_DarkWood_Floor': 'Dark Wood Floor',
      'item_name_lego_lug': 'Block Rug',
      'item_name_wall_lamp': 'Wall Lamp',
      'item_name_warm_lamp': 'Warm Lamp',
      // Login & Auth
      'login': 'Login',
      'signup': 'Sign Up',
      'emailPlaceholder': 'Email',
      'passwordPlaceholder': 'Password',
      'currentPassword': 'Current Password',
      'currentPasswordRequired': 'Please enter current password',
      'newPasswordHint': 'New Password (min 6 chars)',
      'newPasswordRequired': 'Please enter new password',
      'passwordConfirmRequired': 'Please confirm new password',
      'passwordChangedSuccess': 'Password successfully changed',
      'currentPasswordMismatch': 'Current password does not match',
      'requireRecentLogin': 'Please log in again for security',
      'loginWithGoogle': 'Continue with Google',
      'loginWithKakao': 'Continue with Kakao',
      'loginWithApple': 'Continue with Apple',
      'loginWithID': 'Login with ID',
      'idLogin': 'ID Login',
      'guestLogin': 'Guest Login',
      'guestMigrationTitle': 'Save your records safely?',
      'friendSocialLoginTitle': 'Login to share with friends',
      'nestSocialLoginTitle': 'Login to create a nest',
      'guestLoginMigrationDesc': 'When you log in',
      'guestLoginBullet1': 'Records won\'t be lost',
      'guestLoginBullet2': 'Use it on other devices too',
      'guestLoginBullet3': 'Share your day with friends',
      'guestLoginBullet4': 'Grow and decorate your nest',
      'availableAfterSocialLogin': 'Available after social login',
      'noAccountSignup': 'Don\'t have an account? Sign Up',
      'alreadyHaveAccountLogin': 'Already have an account? Login',
      'emailRequired': 'Please enter email',
      'emailInvalid': 'Invalid email format',
      'passwordRequired': 'Please enter password',
      'passwordLengthError': 'Password must be at least 6 characters',
      'namePlaceholder': 'Name',
      'nameRequired': 'Please enter name',
      'passwordConfirmPlaceholder': 'Confirm Password',
      'passwordMismatch': 'Passwords do not match',
      'signupSuccess': 'Sign up successful! Please login.',
      'loginError': 'Login failed',
      'signupError': 'Sign up failed',
      'introTitle': 'Morni',
      'introSubtitle': 'Your mate for the morning',
      'welcomeTitle': 'Welcome!',
      'welcomeDesc':
          'Please enter your nickname and an optional referral code.',
      'nicknameLabel': 'Nickname',
      'nicknamePlaceholder2': 'Enter nickname',
      'referralLabel': 'Referral Code (Optional)',
      'referralPlaceholder': 'Enter referral code (Benefits provided)',
      'referralReward1': 'Both you and your friend ',
      'referralReward2': 'get 100 branches!',
      // Notification Settings
      'serviceNotification': 'Service Notifications',
      'morningDiaryNoti': 'Morning Diary Alert',
      'morningDiaryNotiDesc': 'Remind you to write diary every morning',
      'activityNotification': 'Activity Notifications',
      'wakeUpNoti': 'Wake Up Alert',
      'wakeUpNotiDesc': 'Get notified when a friend wakes you up',
      'cheerMessageNoti': 'Cheer Message Alert',
      'cheerMessageNotiDesc': 'Get notified when a friend sends a cheer',
      'friendNotification': 'Friend Notifications',
      'friendRequestNoti': 'Friend Request Alert',
      'friendRequestNotiDesc': 'Get notified of new friend requests',
      'friendAcceptNoti': 'Friend Accept Alert',
      'friendAcceptNotiDesc': 'Get notified when your request is accepted',
      'friendAcceptNotiTitle': 'Friend Request Accepted',
      'friendAcceptNotiBodyBasic': 'Your friend request has been accepted.',
      'friendAcceptNotiBodyNamed': '{name} accepted your friend request.',
      'friendRejectNoti': 'Friend Reject Alert',
      'friendRejectNotiDesc': 'Get notified when your request is rejected',
      'notificationTime': 'Notification Time',
      'timePickerHour': 'H',
      'timePickerMinute': 'M',
      'nestNotification': 'Nest Notifications',
      'nestInviteNoti': 'Nest Invite Alert',
      'nestInviteNotiDesc': 'Get notified when you receive a nest invite',
      'nestDonationNoti': 'Nest Donation Alert',
      'nestDonationNotiDesc':
          'Get notified when a nest member donates branches',
      // Writing Screen
      'tempSave': 'Draft',
      'saveDraft': 'Save Draft',
      'saveDraftSuccess': 'Draft saved. 📝',
      'saveDraftError': 'Error saving draft. ⚠️',
      'saveDiarySuccess': 'Diary saved! Character woke up! ☀️',
      'saveDiaryError': 'Error saving diary. ⚠️',
      'diaryCompletionTitle': 'Character Woke Up!',
      'diaryCompletionDesc': 'Your character has started the day!',
      'branchEarned': '+{amount} Branch Earned',
      'exitConfirmation': 'Stop Writing?',
      'exitConfirmationDesc': 'Unsaved content will be lost.',
      'writingHint': 'Write down whatever comes to your mind freely.',
      'todayQuestion': 'Today\'s Question',
      'moreWriting': 'Please write a bit more! ✍️',
      'authRequiredForSave': 'Authentication required to save diary',
      'authFailedForSave': 'Authentication failed. Cannot save diary. 🔒',
      // Archive & Diary Detail
      'diaryContent': 'Diary Content',
      'encryptedDiary': 'Encrypted Diary',
      'diaryLoadError': 'Failed to load diary content.',
      'noDiaryContent': 'No diary content.',
      'emotionalAnalysis': 'Emotional Analysis',
      'totalDiaries': 'Total Diaries',
      'consecutiveDaysLabel': 'Consecutive',
      'days': ' Days',
      // Common
      'edit': 'Edit',
      'yes': 'Yes',
      'no': 'No',
      'equipped': 'Equipped',
      'stampEquipped': 'Equipped',
      'unequipped': 'Unequipped',
      'item_name_heart_glass': 'Heart Glasses',
      'item_name_blue_ribbon': 'Blue Ribbon',
      'item_name_pink_mupler': 'Pink Scarf',
      'item_name_necktie': 'Necktie',
      'item_name_plogeyes': 'Frog Eyes',
      'item_name_sprout': 'Sprout',
      'item_name_crown': 'Crown',
      'item_name_wood_glass': 'Wood Glasses',
      'item_name_space_clothes': 'Space Suit',
      'item_name_prog_clothes': 'Frog Suit',
      'item_name_superb_bird_clothes': 'Superb Bird Suit',
      'item_name_humming_bird_clothes': 'Hummingbird Suit',
      'item_name_knight_helm': 'Knight Helm',
      'item_name_castle_candle': 'Castle Candle',
      'item_name_castle_knight_statue': 'Knight Statue',
      'item_name_castle_treasure_chest': 'Treasure Chest',
      'item_name_castle_gargoyle_statue': 'Gargoyle Statue',
      'decorateCharacter': 'Decorate',
      'unequipAll': 'Unequip All',
      'removeAllProps': 'Remove All',
      'showOwnedOnly': 'Show Owned Only',
      'bulkPurchase': 'Bulk Purchase',
      'bulkPurchaseConfirm':
          'There are unowned items.\nDo you want to purchase them all?',
      'totalPrice': 'Total: ',
      'purchaseAndSaveSuccess': 'Purchase & Save Complete! ✨',
      'all': 'All',
      'head': 'Head',
      'face': 'Face',
      'clothes': 'Clothes',
      'accessory': 'Accessory',
      'viewDiaryContent': 'View Diary Content',
      'suspensionTitle': 'Suspension Notice',
      'unsuspendTitle': 'Unsuspend User',
      'suspensionContent':
          'Service access has been temporarily restricted due to community guideline violations.',
      'remainingTimeTitle': 'Time remaining until lifted',
      'permanentSuspension': 'Permanent Suspension',
      'daysRemaining': '{days}d {hours}h remaining',
      'hoursRemaining': '{hours}h {minutes}m remaining',
      'minutesRemaining': '{minutes}m remaining',
      'suspensionReason': 'Reason: {reason}',
      'reason_community_violation': 'Community Guideline Violation',
      // Friend Room
      'sendCheerMessage': 'Send Cheer',
      'resendAfterSeconds': 'Resend in {seconds}s',
      'sentHistory': 'Sent History',
      'friend': 'friend',
      'cheerMessageHint': 'Leave a cheer message',
      'cheerMessageSent': 'Cheer message sent! 💌',
      'cheerMessageSendFailed': 'Failed to send cheer message.',
      'leave': 'Leave',
      'noSentMessages': 'No messages sent yet',
      'userReport': 'User Report',
      'reportReasonSelect': 'Please select a reason.',
      'reportSubmitted': 'Report submitted.',
      'reportError': 'Error submitting report.',
      'reportReasonInappropriate': 'Inappropriate Content',
      'reportReasonAbusive': 'Abusive Language',
      'reportReasonSpam': 'Spam/Ads',
      'reportReasonOther': 'Other',
      'deleteFriendConfirm':
          'Do you want to delete {nickname} from your friend list?',
      'delete': 'Delete',
      'friendDeleted': 'Friend deleted.',
      'friendDeleteError': 'Error deleting friend.',
      // Nest Room
      'nest': 'Nest',
      'nestList': 'Nest List',
      'participatingNests': 'Participating Nests',
      'myNests': 'My Nests',
      'createNest': '+ Create Nest',
      'nestLevel': 'Lv.{level}',
      'nestPeopleCount': '{current}/{max}',
      'createdAt': 'Created At',
      'lastActivity': 'Last activity: {time}',
      'todayActivity': 'Today activity',
      'yesterdayActivity': 'Yesterday activity',
      'hoursAgo': '{hours} hours ago',
      'minutesAgo': '{minutes} minutes ago',
      'justNow': 'Just now',
      'recentActivity': 'Recent activity',
      'createNestTitle': 'Create Nest',
      'nestName': 'Nest Name',
      'enterNestName': 'Enter nest name',
      'maxPeople': 'Max People',
      'isPublic': 'Public/Private',
      'public': 'Public',
      'private': 'Private',
      'create': 'Create',
      'memo': 'Memo',
      'unknown': 'Unknown',
      'nestEditTitle': 'Edit Nest',
      'collectGajiTitle': 'Collect Branches',
      'nestInvitePopupTitle': 'Nest Invite',
      'nestCreateTitle': 'Create Nest',
      'nestNoParticipating': 'No nests joined yet',
      'nestNoMyNests': 'No nests created yet',
      'nestCreateNew': 'Create a new nest!',
      'nestInviteButton': '+ Invite to Nest',
      'nestPlaceholderDesc': 'Our nest story',
      'nestActivityJustNow': 'Just now',
      'nestActivityDaysAgo': '{days} days ago',
      'nestActivityHoursAgo': '{hours} hours ago',
      'nestActivityMinutesAgo': '{minutes} minutes ago',
      'nestEnter': 'Enter >',
      'nestInvite': 'Nest Invite',
      'nestDonation': 'Nest Donation',
      'nestInviteTitle': 'New Nest Invite',
      'nestLabel': 'Nest: {name}',
      'nestInvitePlaceholder': 'Enter friend nickname to invite',
      'nestSelfInviteError': 'You cannot invite yourself.',
      'nestUserNotFoundError': 'User not found.',
      'nestAlreadyMemberError': 'User is already in the nest.',
      'nestInviteSent': 'Invite sent to {nickname}.',
      'nestInviteFailed': 'Invite failed: {error}',
      'nestCollectHint': 'Enter amount to collect',
      'nestCollectButton': 'Collect',
      'nestInvalidAmount': 'Please enter a valid number.',
      'nestNotEnoughGaji': 'Cannot collect more than you have.',
      'nestCollectSuccessTitle': 'Collect Complete',
      'nestCollectSuccessDesc': 'Collected {amount} branches!',
      'nestManageTitle': 'Manage Nest',
      'nestNameHint': 'Enter nest name',
      'nestDescHint': 'Enter nest description (max 15 chars)',
      'nestUpdateSuccess': 'Nest info updated!',
      'nestCreateSuccess': 'Nest created! ✨',
      'nestMyStreak': 'My streak: {days} days!',
      'nestPokeCooldown': 'Wait! Resend in {seconds}s.',
      'nestPokeSuccess': 'Poked {nickname}!',
      'nestPokeDescription': '{nickname}: {days} days streak!',
      'nestNoMembers': 'No members yet.',
      'errorOccurred': 'An error occurred.',
      'dayUnit': 'd',
      'nestMaxCountError': 'You can only create up to 2 nests.',
      'nestInvalidDonateAmount':
          'Please enter a valid amount of branches to donate.',
      'nestNotEnoughGajiError': 'Not enough branches in your account.',
      'nestEmptyMessageError': 'Please enter a message.',
      'nestEmptyNameError': 'Please enter a nest name.',
      'nestFullTitle': 'Nest Full',
      'nestFullError': 'The nest is full and you cannot join.',
      'nestLeaveConfirm': 'Do you want to leave \'{name}\' nest?',
      'nestDeleteConfirm':
          'Do you want to delete \'{name}\' nest?\nAll members will be removed and cannot be recovered.',
      'nestLeaveTitle': 'Leave Nest',
      'nestDeleteTitle': 'Delete Nest',
      'nestDeleteSuccess': 'Nest deleted.',
      'nestLeaveSuccess': 'You left the nest.',
      'nestWithdraw': 'Leave',
      'nestUpgradeTitle': 'Nest Upgrade',
      'nestUpgradeConfirm':
          'Would you like to upgrade your nest to Level {level}?\nThe background will change, member limit will increase to {maxCapacity},\nand you will get a +{bonusPercent}% branch bonus on diaries.',
      'nestUpgradeConfirmMaxLevel':
          'Would you like to upgrade your nest to Level {level}?\nThe background will change and you will get a +{bonusPercent}% branch bonus on diaries.',
      'nestUpgradeSuccess': 'The nest has been upgraded to Level {level}!',
      'nestUpgrade': 'Upgrade',
      'upgrade': 'Upgrade',
      'nestBuffActive': 'Diary branch +{bonus}% buff active!',
      'nestUpgradeNotEnoughGaji': 'Not enough branches. (1000 required)',
      'todaySpeakTitle': 'Today\'s Word',
      'previousDayBtn': '< Prev',
      'nextDayBtn': 'Next >',
      'noTodaySpeakRecords': 'No words recorded today.',
      'unknownUser': 'Unknown',
      'deleteTodaySpeakTitle': 'Are you sure you want to delete?',
      'alreadyPostedTodaySpeak': 'You have already posted today.',
      'todaySpeakHint': 'Leave a word for today..',
      'todaySpeakWrite': 'Write',
      'todaySpeakRewardTitle': 'Reward Earned!',
      'todaySpeakRewardDesc': 'You earned 10 branches for today\'s word!',
      'item_name_bubble_bubble_fish_world': 'Bubble Bubble Fish World',
      'item_name_none': 'None',
      'none': 'None',
      'window': 'Window',
      'inviteCompleted': 'Invite completed',
      'nightlyReminderTitle': 'Please write today\'s diary!',
      'nightlyReminderBody':
          'You haven\'t written your diary yet. If you don\'t write it, your consecutive record will be lost!',
      'morningReminderTitle':
          'Good morning! It\'s time to write your morning diary ☀️',
      'morningReminderBody': 'Start your day fresh by leaving a diary!',
      'notiMsgWakeUp': '{name} is waking you up! ⏰',
      'notiMsgWakeUpPoke': '👉 {name} poked you in the [{nestName}] nest!',
      'notiMsgFriendRequest': '👋 {name} sent you a friend request!',
      'notiMsgFriendAccept': '{name} accepted your friend request.',
      'notiMsgFriendReject': '{name} rejected your friend request.',
      'notiMsgCheerTitle': '{name} sent you a cheer!',
      'notiMsgReplyTitle': '{name} sent a reply!',
      'notiMsgCheer': '{name} sent you a cheer.',
      'notiMsgCheerWithContent': '{message}',
      'notiMsgReplyWithContent': '{message}',
      'notiMsgNestInvite': '{name} invited you to the \'{nestName}\' nest!',
      'notiMsgNestInviteAccept':
          'You accepted the invitation to the \'{nestName}\' nest.',
      'notiMsgNestInviteReject':
          'You rejected the invitation to the \'{nestName}\' nest.',
      'notiMsgNestDonation':
          '{name} donated {amount} branches to the [{nestName}] nest!',
      'notiMsgNestUpgrade':
          '🎉 The [{nestName}] nest has been upgraded to level {level}!',
      'notiMsgMemoLike': '❤️ {name} sent a heart to your memo!',
      'notiMsgReportResultDone':
          'The memo you reported has been deleted. Thank you.',
      'notiMsgReportResultSuspend':
          'The user you reported has been suspended for {duration}. You received 100 branches.',
      'notiMsgReportResultReject': 'Your report was rejected. Reason: {reason}',
      'notiMsgReportViolator':
          'Your memo was reported and deleted for violating our community guidelines.',
      'notiMsgReferralReward': 'You received 100 branches for a referral!',
      'notiMsgChallenge': '{completedStatus}: {title}',
      'friendRejectShort': 'Friend Request Rejected',
      'cheerMessage': 'Cheer Message',
      'characterEvolutionTitle': 'Character Evolution',
      'challengeComplete': 'Challenge Completed',
      'referralReward': 'Referral Reward',
      'refreshShopTitle': 'Refresh Shop',
      'refreshShopDesc':
          'Do you want to refresh the Today\'s Shop items after watching an ad?',
      'refreshShopSuccess': 'Shop items refreshed! ✨',
      'refreshShopFreeTitle': 'Free Refresh',
      'refreshShopFreeDesc': 'Do you want to use your daily free refresh?',
      'refreshShopLimitTitle': 'Limit Reached',
      'refreshShopLimitDesc':
          'You have used all refreshes for today. (1 Free + 3 Ads)',
      'shop_tutorial_1_title': "Today's Shop 🎁",
      'shop_tutorial_1_text':
          "At midnight every day, new treasures arrive! 🎁✨\nDecorate your stunning room and character with random items!",
      'shop_tutorial_refresh_title': "Refresh Shop 🔄",
      'shop_tutorial_refresh_text':
          "Don't like today's items? You can refresh the shop for new ones! (1 Free + 3 Ads daily)",
      'shop_tutorial_2_title': "Short on Branches? 📽️",
      'shop_tutorial_2_text':
          "Seeing furniture you've set your heart on? Watch an ad to get a branch bonus and complete your dream room faster!",
      'deco_tutorial_filter_title': "Find Gifts 🔍",
      'deco_tutorial_filter_text':
          "Tap 'Show Owned Items' to easily find the gift you just received!",
      'deco_tutorial_select_title': "Select Props ✨",
      'deco_tutorial_select_text':
          "Touch the gift you just received to place it in the room!",
      'deco_tutorial_memo_title': "Leave a Memo 📝",
      'deco_tutorial_memo_text':
          "Write a memo so friends can see it when they visit your room!\nHow about sharing today's mood or a message for your friends?",
      'deco_tutorial_save_title': "Save Room 💾",
      'deco_tutorial_save_text':
          "If you're happy with your room, tap the 'Save' button!",
      'deco_tutorial_move_title': "Place as You Like ✨",
      'deco_tutorial_move_text':
          "Drag the selected prop to any position you want! You can freely decorate your room.",
      'deco_tutorial_memo_place_title': "Place Memo 📝",
      'deco_tutorial_memo_place_text':
          "You can also move your written memo to any position. Try placing it in a nice spot!",
      'write_tutorial_blur_title': "Incognito Mode 🤫",
      'write_tutorial_blur_text':
          "You can blur the content with the top button! Useful for writing secret stories you don't want anyone to see.",
      'write_tutorial_draft_title': "It's Okay to Pause 📝",
      'write_tutorial_draft_text':
          "You can save what you're writing as a draft. If you're busy, save it for now and come back to it later!",
      'write_tutorial_mood_title': "How's Your Mood Today? ✨",
      'write_tutorial_mood_text':
          "Pick today's mood! You can use the emoticons you selected in Room Decor - Emoticons here.",
      'write_tutorial_free_title': "Write Your Story ✍️",
      'write_tutorial_free_text':
          "Now, freely write your precious stories here!\n(Don't worry, tutorial diaries aren't actually saved! ✨)\n\nOh! You need to write at least 10 characters to save~ ✨",
      'write_tutorial_save_title': "Save Diary 💾",
      'write_tutorial_save_text':
          "When you're done writing, tap this button to complete!\nA special gift might be waiting for you! 🎁",
      'main_tutorial_diary_title': "Write Today's First Diary ✍️",
      'main_tutorial_diary_text':
          "Hi! Welcome to Morni. How's your mood today? Tap here to leave your first record!",
      'main_tutorial_deco_title': "Check Gifts 🎁",
      'main_tutorial_deco_text':
          "Shall we place the gift you just received in the room?\nTap the 'Room Decor' button!",
      'main_tutorial_shop_title': "Explore Shop 🛍️",
      'main_tutorial_shop_text':
          "Your decorating skills are amazing! Now, explore more items in the shop!",
      'tutorial_complete_reward_title': "Tutorial Reward",
      'tutorial_complete_reward_desc':
          "You've received 50 branches as a tutorial completion reward!",
      'skip_tutorial_title': "End Tutorial",
      'skip_tutorial_desc':
          "Do you want to end the tutorial?\nYou won't be able to receive the completion reward if you stop now.",
      'social_tutorial_title': "Play Together with Friends! 🤝",
      'social_tutorial_text':
          "Wondering how other friends decorated their rooms? Add friends to see! You can check their consecutive diary streaks and visit their rooms. If you like a room, feel free to take some inspiration!",
      'nest_tutorial_title': "Cozy Life in the Nest! 🪹",
      'nest_tutorial_text':
          "Want a closer bond? Share your diary streaks with friends in a nest, wake each other up, and share 'Today's Word'. As the nest grows, so does your branch bonus!",
      'archive_tutorial_title': "Precious Records 📅",
      'archive_tutorial_text':
          "In Records, you can check all your precious diary entries. See your daily moods at a glance on the calendar!",
    },
    'ko': {
      'settings': '설정',
      'account': '계정',
      'changeNickname': '닉네임 변경',
      'email': '이메일',
      'security': '보안',
      'biometricAuth': '생체 인증',
      'biometricAuthDescEnabled': '앱 실행 시 인증 필수',
      'biometricAuthDescDisabled': '생체 인증으로 앱 보호',
      'changePassword': '비밀번호 변경',
      'appSettings': '앱 설정',
      'writingBlur': '글 작성 블러 기본값',
      'writingBlurDescEnabled': '기본적으로 일기 내용 가림',
      'writingBlurDescDisabled': '기본적으로 일기 내용 표시',
      'notificationSettings': '알림 설정',
      'language': '언어',
      'info': '정보',
      'versionInfo': '버전 정보',
      'termsOfService': '서비스 이용약관',
      'privacyPolicy': '개인정보 처리방침',
      'termsAndPrivacy': '이용약관',
      'faq': '자주 묻는 질문',
      'support': '문의하기',
      'logout': '로그아웃',
      'deleteAccount': '회원탈퇴',
      'nicknamePlaceholder': '새 닉네임 입력',
      'cancel': '취소',
      'change': '변경',
      'confirm': '확인',
      'retry': '다시 시도',
      'update': '업데이트',
      'later': '나중에 하기',
      'updateNotice': '업데이트 안내',
      'error': '오류',
      'nicknameLengthError': '닉네임은 2자 이상이어야 합니다',
      'nicknameTakenError': '이미 사용 중인 닉네임입니다',
      'korean': '한국어',
      'english': 'English',
      'japanese': '일본어',
      'selectLanguage': '언어 선택',
      'collectMyMemos': '내 메모 모아보기',
      'myPage': '기록',
      'diaryWritingInfo': '일기 작성 정보',
      'branch': '가지',
      'pointHistoryTitle': '가지 상세 내역',
      'noPointHistory': '가지 사용 내역이 없습니다.',
      'historyPurchaseTheme': '테마 구매',
      'historyPurchaseBackground': '배경 구매',
      'historyPurchaseWallpaper': '벽지 구매',
      'historyPurchaseProp': '소품 구매',
      'historyPurchaseEmoticon': '이모티콘 구매',
      'historyPurchaseFloor': '바닥 구매',
      'historyPurchaseWindow': '창문 구매',
      'historyPurchaseCharacterItem': '아이템 구매',
      'historyDiaryReward': '일기 작성 보상',
      'historyAdReward': '광고 시청 보상',
      'historyChallengeReward': '도전과제 달성',
      'historyDonation': '둥지 기부',
      'historyNestReward': '오늘의 한마디 보상',
      'historyShopTutorialReward': '상점 튜토리얼 완료 보상',
      'historyStickyNote': '메모 작성',
      'home': '홈',
      'challenge': '도전과제',
      'friends': '친구',
      'shop': '상점',
      'buyItem': '구매하기',
      'todayShop': '오늘의 상점',
      'allItems': '전체 상품',
      'newItems': '신상품',
      'writeDiary': '일기 작성하기',
      'wallpaper': '벽지',
      'background': '배경',
      'prop': '소품',
      'floor': '바닥',
      'character': '캐릭터',
      'emoticon': '이모티콘',
      'watchAdGetBranch': '광고 보고 가지 받기',
      'completed': '일기 작성 완료',
      'watch': '보기',
      'unowned': '미보유',
      'purchaseConfirm': '{item}을(를) 구매하시겠습니까?',
      'salePrice': 'SALE! {original} -> {discounted} 가지',
      'notEnoughBranch': '가지가 부족합니다.',
      'purchaseSuccess': '{item}을(를) 구매했습니다.',
      'decorate': '꾸미기',
      'owned': '보유중',
      'sale': 'SALE',
      'notifications': '알림',
      'markAllAsRead': '모두 읽음',
      'loadingNotifications': '알림을 불러오는 중이에요',
      'pleaseWait': '잠시만 기다려주세요',
      'errorLoadingNotifications': '알림을 불러오는 중 오류가 발생했습니다',
      'tryAgainLater': '잠시 후 다시 시도해주세요',
      'noNotifications': '알림이 없습니다',
      'noNotificationsDesc': '새로운 소식이 생기면 이곳에 알려드릴게요',
      'replyFrom': '{username}님의 답장',
      'cheerFrom': '{username}님의 응원',
      'wakeUpAlert': '깨우기 알림',
      'nestPokeAlert': '찌르기 알림',
      'friendRequest': '친구 요청',
      'accept': '수락',
      'reject': '거절',
      'replyCompleted': '답장 완료',
      'reply': '답장',
      'free': '무료',
      'ad': '광고',
      'skip': '스킵',
      'stickyNoteHint': '짧은 메시지를 남겨보세요',
      'decorateRoom': '방 꾸미기',
      'decorationSaved': '설정이 저장되었습니다! ✨',
      'unownedItemsWarning':
          '배치된 항목 중 아직 보유하지 않은 아이템이 있어요!\n미보유 아이템은 상점에서 획득할 수 있습니다.\n뺀 상태로 저장할까요?',
      'saveFailed': '저장 실패: ',
      'save': '저장',
      'memo': '메모',
      'noProps': '구매한 소품이 없습니다. 상점에서 구매해 보세요!',
      'stickyNoteLimit': '메모는 하루에 한 번만 작성할 수 있습니다. ✍️',
      'noStickyNote': '보관 중인 메모 노트가 없습니다. 상점에서 구매해 주세요. 📦',
      'deleteStickyNote': '메모를 삭제하시겠습니까? 🗑️',
      'stickyNoteAdded': '메모가 추가되었습니다! (5가지 차감) 📝',
      'notEnoughPoints': '가지가 부족합니다. (5가지 필요)',
      'myReferralCode': '내 추천인 코드',
      'referralCodeCopied': '추천인 코드가 복사되었습니다.',
      // Main & Strings
      'greetingMorning': '좋은 아침이에요!',
      'greetingAfternoon': '좋은 오후예요!',
      'greetingEvening': '좋은 저녁이에요!',
      'consecutiveDays': '{days}일 연속 기록 중 🔥',
      'nicknameIntro': '반가워요! 사용하실 닉네임을 입력해주세요.',
      'start': '시작하기',
      'kakaoLogin': '카카오 로그인',
      'appleLogin': 'Apple 로그인',
      'nicknameChanged': '닉네임이 변경되었습니다! ✨',
      'errorSavingSettings': '설정 저장 중 오류가 발생했습니다: ',
      'enterNewNickname': '새 닉네임 입력',
      // Social
      'friendsTitle': '친구',
      'friendsCount': '{count}명',
      'addFriendEmpty': '친구를 추가해\n보세요',
      'newFriendRequests': '새로운 친구 요청',
      'friendRequestSent': '{nickname}님께\n친구 요청을 보냈습니다!',
      'youBecameFriends': '{nickname}님과 친구가 되었습니다!',
      'enterFriendNickname': '친구 닉네임 입력',
      'request': '요청',
      'invite': '초대하기',
      'userNotFound': '해당 닉네임의 사용자를 찾을 수 없습니다.',
      'selfRequestError': '자신에게는 친구 요청을 보낼 수 없습니다.',
      'addFriendButton': '+친구 추가',
      'friendRequestRejection': '친구 요청이 거절되었습니다.',
      'wakeUp': '깨우기',
      'written': '작성 완료',
      'wakeUpSuccess': '{nickname}님을 깨웠습니다! ⏰',
      'wakeUpFailed': '깨우기 요청 실패',
      'secondsUnit': '{seconds}초',
      // Challenge
      'challengesTitle': '도전과제',
      'challengesProgress': '도전과제 달성 수',
      'challengeCompleted': '도전과제 달성!',
      'challengeDetailCurrent': '현재',
      'challengeDetailTarget': '목표',
      'challengeDetailInfo': '도전과제 상세',
      'challengeDetailWarningTitle': '주의사항',
      'challengeDetailWarningDesc': '하루라도 빠지면 연속 기록이 0으로 초기화됩니다!',
      'challengeDetailCurrentRecord': '현재 기록',
      'challengeDetailRemaining': '같은 계열 남은 도전과제',
      'challengeDetailReward': '보상',
      'challengeDetailCurrentLabel': '현재',
      'challenge_dawn_start_title': '새벽의 시작',
      'challenge_dawn_start_desc': '오전 6시 이전에 일기 1회 작성하기',
      'challenge_steady_habit_title': '꾸준한 습관',
      'challenge_steady_habit_desc': '3일 연속 일기 작성하기',
      'challenge_morning_person_title': '진정한 아침형 인간',
      'challenge_morning_person_desc': '7일 연속 일기 작성하기',
      'challenge_rich_room_title': '풍성한 방',
      'challenge_rich_room_desc': '소품 3개 이상 구매하기',
      'challenge_social_king_title': '마당 넓은 주인',
      'challenge_social_king_desc': '친구 5명 맺기',
      'challenge_diary_master_title': '일기의 달인',
      'challenge_diary_master_desc': '누적 일기 30개 작성하기',
      'challenge_streak_14_title': '2주 연속 기록',
      'challenge_streak_14_desc': '14일 연속 일기 작성하기',
      'challenge_streak_21_title': '3주 연속 기록',
      'challenge_streak_21_desc': '21일 연속 일기 작성하기',
      'challenge_streak_30_title': '한 달의 기적',
      'challenge_streak_30_desc': '30일 연속 일기 작성하기',
      'challenge_friend_1_title': '첫 친구',
      'challenge_friend_1_desc': '첫 친구 만들기',
      'challenge_friend_10_title': '인기쟁이',
      'challenge_friend_10_desc': '친구 10명 만들기',
      'challenge_friend_20_title': '마당발',
      'challenge_friend_20_desc': '친구 20명 만들기',
      'challenge_prop_1_title': '첫 소품',
      'challenge_prop_1_desc': '소품 1개 구매하기',
      'challenge_prop_5_title': '꾸미기 꿈나무',
      'challenge_prop_5_desc': '소품 5개 구매하기',
      'challenge_prop_10_title': '맥시멀리스트',
      'challenge_prop_10_desc': '소품 10개 구매하기',
      'challenge_fashion_3_title': '패셔니스타',
      'challenge_fashion_3_desc': '캐릭터 아이템 3개 구매하기',
      'challenge_fashion_5_title': '트렌드세터',
      'challenge_fashion_5_desc': '캐릭터 아이템 5개 구매하기',
      'challenge_bg_1_title': '기분 전환',
      'challenge_bg_1_desc': '배경 1개 구매하기',
      'challenge_bg_3_title': '분위기 메이커',
      'challenge_bg_3_desc': '배경 3개 구매하기',
      'challenge_level_2_title': '첫 성장',
      'challenge_level_2_desc': '캐릭터 레벨 2 달성하기',
      'challenge_level_3_title': '쑥쑥 성장',
      'challenge_level_3_desc': '캐릭터 레벨 3 달성하기',
      'challenge_level_4_title': '거의 다 왔어',
      'challenge_level_4_desc': '캐릭터 레벨 4 달성하기',
      'challenge_level_5_title': '폭풍 성장',
      'challenge_level_5_desc': '캐릭터 레벨 5 달성하기',
      'challenge_memo_1_title': '첫 메모',
      'challenge_memo_1_desc': '첫 메모 작성하기',
      'challenge_memo_3_title': '메모 수집가',
      'challenge_memo_3_desc': '메모 3개 작성하기',
      'challenge_memo_10_title': '메모 매니아',
      'challenge_memo_10_desc': '메모 10개 작성하기',
      'challenge_memo_30_title': '메모 마스터',
      'challenge_memo_30_desc': '메모 30개 작성하기',
      'deleteAccountConfirmDesc': '정말로 탈퇴하시겠습니까?\n모든 데이터가 영구적으로 삭제됩니다.',
      'passwordConfirmHint': '비밀번호 확인',
      'deleteAccountConsent': '안내 사항을 모두 확인하였으며, 탈퇴에 동의합니다.',
      'noDiaryForDay': '이 날은 일기를 작성하지 않았습니다',
      'diaryRecordForDay': '{date} 기록',
      'biometricAuthReasonPastRecords': '과거 기록을 확인하기 위해 인증이 필요합니다',
      'biometricAuthFailed': '생체 인증에 실패했습니다. 🔒',
      'noMemos': '작성한 메모가 없습니다',
      'myMemos': '내 메모',
      'fullDateFormat': '{year}년 {month}월 {day}일 ({weekday})',
      'monthDayFormat': '{month}월 {day}일',
      'monthDayFormatWithWeekday': '{month}월 {day}일 ({weekday})',
      'state_egg': '알 🥚',
      'state_cracking': '금이 간 알 🥚✨',
      'state_hatching': '부화 중 🐣',
      'state_baby': '새끼 새 🐥',
      'state_young': '아기 새 🐦',
      'state_adult': '귀여운 새 🕊️',
      'state_sleeping': '수면 중 💤',
      'weekday_mon': '월',
      'weekday_tue': '화',
      'weekday_wed': '수',
      'weekday_thu': '목',
      'weekday_fri': '금',
      'weekday_sat': '토',
      'weekday_sun': '일',
      'noQuestion': '질문이 없습니다.',
      'previous': '이전',
      'next': '다음',
      'gift_popup_title': '특별한 선물 🎁',
      'gift_popup_welcome': '첫 방문을 축하합니다! 🎉',
      'gift_popup_desc': '특별한 선물이 도착했어요.',
      'receive': '받기',
      'characterInfo': '캐릭터 정보',
      // AppDialog
      'biometricErrorTitle': '생체 인증 실패',
      'biometricErrorDesc': '생체 인증에 실패했습니다. 다시 시도하거나 로그아웃할 수 있습니다.',
      'logoutTitle': '로그아웃',
      'logoutDesc': '정말 로그아웃 하시겠습니까?',
      'deleteAccountTitle': '회원탈퇴',
      'deleteAccountDesc': '정말 회원탈퇴 하시겠습니까?\n모든 데이터가 삭제되며 복구할 수 없습니다.',
      'pageNotFound': '페이지를 찾을 수 없습니다',
      'addFriendTitle': '친구 추가',
      'cheerMessageTitle': '응원 메시지',
      'exitWritingTitle': '작성을 중단하시겠어요?',
      'exitWritingDesc': '지금 중단하면 작성 중인 내용은 저장되지 않아요. (임시저장을 활용해 보세요!)',
      'keepWriting': '계속 작성',
      'stop': '중단',
      'sentMessagesTitle': '보낸 메시지',
      'purchaseTitle': '아이템 구매',
      'purchaseCompleteTitle': '구매 완료',
      'levelUpTitle': '🎊 축하합니다! 🎊',
      'levelUpDesc': '캐릭터가 새로운 단계로 성장했어요!',
      'continueGrowth': '앞으로도 꾸준히 성장을 도와주세요.',
      'maxLevel': '최대 레벨',
      'adRewardTitle': '가지 획득!',
      'adRewardDesc': '광고 시청 보상으로\n20 가지를 획득했습니다!',
      'deleteFriendTitle': '친구 삭제',
      'deleteFriendDesc': '친구를 삭제하시겠습니까?',
      'reportTitle': '신고하기',
      'report': '신고',
      'ok': '확인',
      'close': '닫기',
      'bonusAdOfferTitle': '🎁 보너스 가지 획득!',
      'bonusAdOfferDesc': '광고를 시청하면 보너스 가지 20개를 드려요!',
      'bonusAdOfferWarning': '※ 광고를 끝까지 시청하지 않고 닫으면 보상이 지급되지 않습니다.',
      'watchAd': '광고 보기',
      // Items (Names)
      'item_name_default': '기본',
      'item_name_stripe': '스트라이프',
      'item_name_check': '체크',
      'item_name_dot': '도트',
      'item_name_flower_sky': '꽃하늘',
      'item_name_pink_lace': '핑크레이스',
      'item_name_red_heart': '빨간하트',
      'item_name_colorful_hexagon': '컬러풀육각형',
      'item_name_Space_Background': '우주',
      'item_name_Castle_Stone_Wall': '중세 성 벽지',
      'item_name_lego_wallpaper': '블럭 벽지',
      'item_name_DarkPanel': '다크 패널',
      'item_name_IvoryClassic': '아이보리 클래식',
      'item_name_light': '라이트',
      'item_name_happy': '행복',
      'item_name_normal': '평범',
      'item_name_sad': '슬픔',
      'item_name_love': '사랑',
      'item_name_angry': '화남',
      'item_name_awkward': '당황',
      'item_name_move': '감동',
      'item_name_sleep': '졸림',
      'item_name_blue_moon': '푸른 달',
      'item_name_blue_moon2': '푸른 달2',
      'item_name_golden_sun': '황금 태양',
      'item_name_starry_night': '별이 빛나는 밤',
      'item_name_alarm_clock': '알람시계',
      'item_name_wood_desk': '원목 책상',
      'item_name_book_desk': '독서대',
      'item_name_wooden_desk_sprite': '원목 책상2',
      'item_name_space_desk': '우주 책상',
      'item_name_space_desk2': '우주 책상2',
      'item_name_space_drawer': '우주 서랍장',
      'item_name_space_drawer2': '우주 서랍장2',
      'item_name_wood_chair': '원목 의자',
      'item_name_wood_bed': '원목 침대',
      'item_name_space_chair': '우주 의자',
      'item_name_space_bed': '우주 침대',
      'item_name_pogeun_sofa': '포근소파',
      'item_name_cozy_bean': '낮잠소파',
      'item_name_pot_1': '식물 화분',
      'item_name_analog_clock': '아날로그 시계',
      'item_name_white_bear': '흰 곰 인형',
      'item_name_pink_chair': '핑크 의자',
      'item_name_blue_chair': '파란 의자',
      'item_name_mug_cup': '머그컵',
      'item_name_wood_cup': '원목 컵',
      'item_name_cloud_watch': '구름 시계',
      'item_name_red_carpet': '레드 카펫',
      'item_name_sticky_note': '메모',
      'item_name_wood': '나무 바닥',
      'item_name_wood2': '나무 바닥2',
      'item_name_pink_wood': '핑크 나무 바닥',
      'item_name_peach_break': '피치피치',
      'item_name_pink_carpet': '핑크 카펫',
      'item_name_alokdalok': '알록달록',
      'item_name_castle_stone': '중세 성 바닥',
      'item_name_space_floor': '우주 바닥',
      'item_name_lego_book_desk': '블럭 독서 책상',
      'item_name_lego_chair': '블럭 의자',
      'item_name_lego_clock': '블럭 시계',
      'item_name_lego_cloth_desk': '블럭 천 책상',
      'item_name_lego_desk': '블럭 책상',
      'item_name_lego_door': '블럭 문',
      'item_name_lego_flower': '블럭 꽃',
      'item_name_lego_frame': '블럭 액자',
      'item_name_lego_frame2': '블럭 액자2',
      'item_name_lego_game_machine': '블럭 게임기',
      'item_name_lego_lamp': '블럭 램프',
      'item_name_lego_mailbox': '블럭 우체통',
      'item_name_lego_piano': '블럭 피아노',
      'item_name_lego_sink': '블럭 세면대',
      'item_name_lego_floor': '블럭 바닥',
      'item_name_DarkWood_Floor': '어두운 나무 바닥',
      'item_name_lego_lug': '블럭 러그',
      'item_name_wall_lamp': '벽조명',
      'item_name_warm_lamp': '따뜻한 램프',
      // Login & Auth
      'login': '로그인',
      'signup': '회원가입',
      'emailPlaceholder': '이메일',
      'passwordPlaceholder': '비밀번호',
      'currentPassword': '현재 비밀번호',
      'currentPasswordRequired': '현재 비밀번호를 입력해주세요',
      'newPasswordHint': '새 비밀번호 (6자 이상)',
      'newPasswordRequired': '새 비밀번호를 입력해주세요',
      'passwordConfirmRequired': '비밀번호 확인을 입력해주세요',
      'passwordChangedSuccess': '비밀번호가 변경되었습니다',
      'currentPasswordMismatch': '현재 비밀번호가 일치하지 않습니다',
      'requireRecentLogin': '보안을 위해 다시 로그인 후 시도해주세요',
      'loginWithGoogle': '구글로 계속하기',
      'loginWithKakao': '카카오로 계속하기',
      'loginWithApple': '애플로 계속하기',
      'loginWithID': 'ID로 로그인',
      'idLogin': 'ID 로그인',
      'guestLogin': '임시 로그인',
      'guestMigrationTitle': '작성한 기록을 안전하게 저장할까요?',
      'friendSocialLoginTitle': '친구와 함께 하려면 로그인을 해주세요',
      'nestSocialLoginTitle': '둥지를 만들려면 로그인을 해주세요',
      'guestLoginMigrationDesc': '로그인하면',
      'guestLoginBullet1': '기록이 사라지지 않아요',
      'guestLoginBullet2': '다른 기기에서도 이어서 사용 가능',
      'guestLoginBullet3': '친구와 함께 하루를 공유할 수 있어요',
      'guestLoginBullet4': '둥지를 성장시키고 꾸밀 수 있어요',
      'availableAfterSocialLogin': '소셜 로그인 후 이용 가능합니다',
      'noAccountSignup': '계정이 없으신가요? 회원가입',
      'alreadyHaveAccountLogin': '계정이 있으신가요? 로그인',
      'emailRequired': '이메일을 입력해주세요',
      'emailInvalid': '올바른 이메일 형식이 아닙니다',
      'passwordRequired': '비밀번호를 입력해주세요',
      'passwordLengthError': '비밀번호는 최소 6자 이상이어야 합니다',
      'namePlaceholder': '이름',
      'nameRequired': '이름을 입력해주세요',
      'passwordConfirmPlaceholder': '비밀번호 확인',
      'passwordMismatch': '비밀번호가 일치하지 않습니다',
      'signupSuccess': '회원가입이 완료되었습니다! 로그인해주세요.',
      'loginError': '로그인 실패',
      'signupError': '회원가입 실패',
      'introTitle': 'Morni',
      'introSubtitle': '아침을 함께하는 당신의 메이트',
      'welcomeTitle': '환영합니다!',
      'welcomeDesc': '사용하실 닉네임과 추천인 코드를 입력해주세요.',
      'nicknameLabel': '닉네임',
      'nicknamePlaceholder2': '닉네임을 입력하세요',
      'referralLabel': '추천인 코드 (선택)',
      'referralPlaceholder': '추천인 코드가 있다면 입력해주세요 (혜택 제공)',
      'referralReward1': '나와 친구가 같이 ',
      'referralReward2': '100개 받아요!',
      // Notification Settings
      'serviceNotification': '서비스 알림',
      'morningDiaryNoti': '아침 일기 알림',
      'morningDiaryNotiDesc': '아침마다 일기 작성을 잊지 않도록 알려드려요',
      'activityNotification': '활동 알림',
      'wakeUpNoti': '깨우기 알림',
      'wakeUpNotiDesc': '친구가 나를 깨웠을 때 알림을 받아요',
      'cheerMessageNoti': '응원 메시지 알림',
      'cheerMessageNotiDesc': '친구가 응원 메시지를 남겼을 때 알림을 받아요',
      'friendNotification': '친구 알림',
      'friendRequestNoti': '친구 요청 알림',
      'friendRequestNotiDesc': '새로운 친구 요청이 오면 알려드려요',
      'friendAcceptNoti': '친구 수락 알림',
      'friendAcceptNotiDesc': '상대방이 내 친구 요청을 수락하면 알려드려요',
      'friendAcceptNotiTitle': '친구 요청 수락',
      'friendAcceptNotiBodyBasic': '친구 요청이 수락되었어요.',
      'friendAcceptNotiBodyNamed': '{name}님이 친구 요청을 수락했어요.',
      'friendRejectNoti': '친구 거절 알림',
      'friendRejectNotiDesc': '내 친구 요청이 거절되었을 때 알림을 받아요',
      'notificationTime': '알림 시간 설정',
      'timePickerHour': '시',
      'timePickerMinute': '분',
      'nestNotification': '둥지 알림',
      'nestInviteNoti': '둥지 초대 알림',
      'nestInviteNotiDesc': '둥지 초대를 받았을 때 알림을 받아요',
      'nestDonationNoti': '가지 기부 알림',
      'nestDonationNotiDesc': '둥지 멤버가 가지를 기부했을 때 알림을 받아요',
      // Writing Screen
      'tempSave': '임시저장',
      'saveDraft': '임시저장',
      'saveDraftSuccess': '임시 저장되었습니다. 📝',
      'saveDraftError': '임시 저장 중 오류가 발생했습니다. ⚠️',
      'saveDiarySuccess': '저장되었습니다! 캐릭터가 깨어났어요! ☀️',
      'saveDiaryError': '저장 중 오류가 발생했습니다. ⚠️',
      'diaryCompletionTitle': '캐릭터가 깨어났어요!',
      'diaryCompletionDesc': '캐릭터가 하루를 시작했어요!',
      'branchEarned': '+{amount} 가지 획득',
      'exitConfirmation': '작성을 중단하시겠어요?',
      'exitConfirmationDesc': '작성 중인 내용은 저장되지 않습니다.',
      'writingHint': '지금 머릿속에 떠오르는 생각을 자유롭게 적어보세요.',
      'todayQuestion': '오늘의 질문',
      'moreWriting': '조금만 더 작성해주세요! ✍️',
      'authRequiredForSave': '일기를 안전하게 저장하기 위해 인증이 필요합니다',
      'authFailedForSave': '인증에 실패하여 일기를 저장할 수 없습니다. 🔒',
      // Archive & Diary Detail
      'diaryContent': '일기 내용',
      'encryptedDiary': '암호화된 일기',
      'diaryLoadError': '일기 내용을 불러오는데 실패했습니다.',
      'noDiaryContent': '일기 내용이 없습니다.',
      'emotionalAnalysis': '감정 분석',
      'totalDiaries': '총 일기',
      'consecutiveDaysLabel': '연속 작성',
      'days': '일',
      // Common
      'edit': '수정',
      'yes': '네',
      'no': '아니오',
      'equipped': '장착됨',
      'stampEquipped': '장착',
      'unequipped': '장착해제',
      'item_name_heart_glass': '하트 안경',
      'item_name_blue_ribbon': '파란 리본',
      'item_name_pink_mupler': '분홍 목도리',
      'item_name_necktie': '넥타이',
      'item_name_plogeyes': '개구리 눈',
      'item_name_sprout': '새싹',
      'item_name_crown': '왕관',
      'item_name_wood_glass': '나무 안경',
      'item_name_space_clothes': '우주복',
      'item_name_prog_clothes': '개굴옷',
      'item_name_superb_bird_clothes': '극락조 새옷',
      'item_name_humming_bird_clothes': '벌새옷',
      'item_name_knight_helm': '기사 투구',
      'item_name_castle_candle': '성 촛대',
      'item_name_castle_knight_statue': '기사 조각상',
      'item_name_castle_treasure_chest': '보물 상자',
      'item_name_castle_gargoyle_statue': '가고일 석상',
      'decorateCharacter': '꾸미기',
      'unequipAll': '모두 해제',
      'removeAllProps': '모두 제거',
      'showOwnedOnly': '보유중인 상품만 보기',
      'bulkPurchase': '일괄구매',
      'bulkPurchaseConfirm': '구매하지 않은 상품이 있습니다.\n일괄 구매하시겠습니까?',
      'totalPrice': '총 합계: ',
      'purchaseAndSaveSuccess': '구매 및 저장이 완료되었습니다! ✨',
      'all': '전체',
      'head': '머리',
      'face': '얼굴',
      'clothes': '옷',
      'accessory': '장식',
      'viewDiaryContent': '일기 내용 보기',
      'suspensionTitle': '이용 제한 안내',
      'unsuspendTitle': '정지 해제',
      'suspensionContent': '커뮤니티 가이드라인 위반으로 인해\n서비스 이용이 일시적으로 제한되었습니다.',
      'remainingTimeTitle': '해제까지 남은 시간',
      'permanentSuspension': '영구 정지',
      'daysRemaining': '{days}일 {hours}시간 남음',
      'hoursRemaining': '{hours}시간 {minutes}분 남음',
      'minutesRemaining': '{minutes}분 남음',
      'suspensionReason': '사유: {reason}',
      'reason_community_violation': '커뮤니티 가이드라인 위반',
      // Friend Room
      'sendCheerMessage': '응원메시지 보내기',
      'resendAfterSeconds': '{seconds}초 후 재전송',
      'sentHistory': '보낸기록',
      'friend': '친구',
      'cheerMessageHint': '친구에게 응원의 메시지를 남겨주세요',
      'cheerMessageSent': '응원 메시지를 보냈습니다! 💌',
      'cheerMessageSendFailed': '응원 메시지 전송에 실패했습니다.',
      'leave': '남기기',
      'noSentMessages': '아직 보낸 메시지가 없어요',
      'userReport': '사용자 신고',
      'reportReasonSelect': '신고 사유를 선택해주세요.',
      'reportSubmitted': '신고가 접수되었습니다.',
      'reportError': '신고 접수 중 오류가 발생했습니다.',
      'reportReasonInappropriate': '부적절한 내용',
      'reportReasonAbusive': '욕설/비하 발언',
      'reportReasonSpam': '스팸/광고',
      'reportReasonOther': '기타',
      'deleteFriendConfirm': '{nickname}님을 친구 목록에서\n삭제하시겠습니까?',
      'delete': '삭제',
      'friendDeleted': '친구가 삭제되었습니다.',
      'friendDeleteError': '친구 삭제 중 오류가 발생했습니다.',
      // Nest Room
      'nest': '둥지',
      'nestList': '둥지 목록',
      'participatingNests': '참여 중인 둥지',
      'myNests': '내가 만든 둥지',
      'createNest': '+ 둥지 만들기',
      'nestLevel': 'Lv.{level}',
      'nestPeopleCount': '{current}/{max}',
      'createdAt': '생성일',
      'lastActivity': '{time} 전 활동',
      'todayActivity': '오늘 활동',
      'yesterdayActivity': '어제 활동',
      'hoursAgo': '{hours}시간',
      'minutesAgo': '{minutes}분',
      'justNow': '방금',
      'recentActivity': '최근 활동',
      'createNestTitle': '둥지 만들기',
      'nestName': '둥지 이름',
      'enterNestName': '둥지 이름을 입력하세요',
      'maxPeople': '최대 인원',
      'isPublic': '공개 설정',
      'public': '공개',
      'private': '비공개',
      'create': '만들기',
      'unknown': '알 수 없음',
      'nestEditTitle': '둥지 수정',
      'collectGajiTitle': '가지 모으기',
      'nestInvitePopupTitle': '둥지 초대',
      'nestCreateTitle': '둥지 만들기',
      'nestNoParticipating': '참여중인 둥지가 없어요',
      'nestNoMyNests': '내가 만든 둥지가 없어요',
      'nestCreateNew': '새로운 둥지를 만들어 보세요!',
      'nestInviteButton': '+ 둥지 초대',
      'nestPlaceholderDesc': '우리의 둥지 이야기',
      'nestActivityJustNow': '방금 전 활동',
      'nestActivityDaysAgo': '{days}일 전 활동',
      'nestActivityHoursAgo': '{hours}시간 전 활동',
      'nestActivityMinutesAgo': '{minutes}분 전 활동',
      'nestEnter': '입장하기 >',
      'nestInvite': '둥지 초대',
      'nestDonation': '둥지 기부',
      'nestInviteTitle': '새로운 둥지 초대',
      'nestLabel': '둥지: {name}',
      'nestInvitePlaceholder': '초대할 친구의 닉네임을 입력하세요',
      'nestSelfInviteError': '자신을 초대할 수 없습니다.',
      'nestUserNotFoundError': '존재하지 않는 닉네임입니다.',
      'nestAlreadyMemberError': '이미 둥지에 있는 사용자입니다.',
      'nestInviteSent': '{nickname}님에게 초대 요청을 보냈습니다.',
      'nestInviteFailed': '초대 실패: {error}',
      'nestCollectHint': '모을 수량을 입력하세요',
      'nestCollectButton': '모으기',
      'nestInvalidAmount': '올바른 숫자를 입력해주세요.',
      'nestNotEnoughGaji': '보유한 가지보다 많이 모을 수 없습니다.',
      'nestCollectSuccessTitle': '모으기 완료',
      'nestCollectSuccessDesc': '가지 {amount}개 모으기 성공!',
      'nestManageTitle': '둥지 관리',
      'nestNameHint': '둥지 이름을 입력하세요',
      'nestDescHint': '둥지 설명을 입력하세요 (최대 15자)',
      'nestUpdateSuccess': '둥지 정보를 수정했습니다!',
      'nestCreateSuccess': '둥지가 생성되었습니다! ✨',
      'nestMyStreak': '나의 연속 기록: {days}일!',
      'nestPokeCooldown': '앗! {seconds}초 뒤에 다시 찌를 수 있어요!',
      'nestPokeSuccess': '{nickname}님을 찔렀어요!',
      'nestPokeDescription': '{nickname}: 연속 {days}일! (더블탭해서 찌르기)',
      'nestNoMembers': '아직 멤버가 없습니다.',
      'errorOccurred': '오류가 발생했습니다.',
      'dayUnit': '일',
      'nestMaxCountError': '최대 2개의 둥지만 만들 수 있습니다.',
      'nestInvalidDonateAmount': '기부할 가지의 수를 정확히 입력해주세요.',
      'nestNotEnoughGajiError': '보유하고 있는 가지가 부족합니다.',
      'nestEmptyMessageError': '한마디를 입력해주세요.',
      'nestEmptyNameError': '둥지 이름을 입력해주세요.',
      'nestFullTitle': '둥지 정원 초과',
      'nestFullError': '10명이 꽉차서 더 이상 입장할 수 없습니다.',
      'nestLeaveConfirm': '\'{name}\' 둥지에서 정말 나가시겠습니까?',
      'nestDeleteConfirm':
          '\'{name}\' 둥지를 정말 삭제하시겠습니까?\n모든 멤버가 탈퇴 처리되며 복구할 수 없습니다.',
      'nestLeaveTitle': '둥지 나가기',
      'nestDeleteTitle': '둥지 삭제',
      'nestDeleteSuccess': '둥지가 삭제되었습니다.',
      'nestLeaveSuccess': '둥지에서 퇴장했습니다.',
      'nestWithdraw': '나가기',
      'nestUpgradeTitle': '둥지 업그레이드',
      'nestUpgradeConfirm':
          '둥지를 레벨 {level}로 업그레이드 하시겠습니까?\n배경이 바뀌고 정원이 {maxCapacity}명으로 늘어납니다.\n(일기 작성 시 가지 +{bonusPercent}% 버프 획득)',
      'nestUpgradeConfirmMaxLevel':
          '둥지를 레벨 {level}로 업그레이드 하시겠습니까?\n배경이 바뀌며 일기 작성 시 가지 +{bonusPercent}% 버프를 획득합니다.',
      'nestUpgradeSuccess': '둥지가 레벨 {level}로 업그레이드 되었습니다!',
      'nestUpgrade': '업그레이드',
      'upgrade': '업그레이드',
      'nestBuffActive': '일기 작성 가지 +{bonus}% 버프 적용중!',
      'nestUpgradeNotEnoughGaji': '가지가 부족합니다. (1000개 필요)',
      'todaySpeakTitle': '오늘의 한마디',
      'previousDayBtn': '< 이전날',
      'nextDayBtn': '다음날 >',
      'noTodaySpeakRecords': '작성된 한마디가 없습니다.',
      'unknownUser': '알 수 없음',
      'deleteTodaySpeakTitle': '삭제하시겠습니까?',
      'alreadyPostedTodaySpeak': '이미 오늘의 한마디를 작성했습니다.',
      'todaySpeakHint': '오늘의 한마디를 남겨보세요..',
      'todaySpeakWrite': '작성',
      'todaySpeakRewardTitle': '보상 획득!',
      'todaySpeakRewardDesc': '오늘의 한마디 보상으로 10가지를 획득했습니다!',
      'item_name_bubble_bubble_fish_world': '보글보글 물고기 월드',
      'item_name_none': '없음',
      'none': '없음',
      'window': '창문',
      'nightlyReminderTitle': '오늘의 일기를 작성해주세요!',
      'nightlyReminderBody': '아직 일기를 작성하지 않았어요. 작성하지 않으면 연속 기록이 날아가요!',
      'morningReminderTitle': '굿모닝! 아침 일기를 작성할 시간이에요 ☀️',
      'morningReminderBody': '상쾌한 하루를 시작하며 일기를 남겨보세요!',
      'notiMsgWakeUp': '{name}님이 당신을 깨우고 있어요! ⏰',
      'notiMsgWakeUpPoke': '👉 [{nestName}] 둥지에서 {name}님이 찔렀습니다!',
      'notiMsgFriendRequest': '👋 {name}님이 친구 요청을 보냈습니다!',
      'notiMsgFriendAccept': '{name}님이 친구 요청을 수락했어요.',
      'notiMsgFriendReject': '{name}님이 친구 요청을 거절했어요.',
      'notiMsgCheerTitle': '{name}님이 응원 메시지를 보냈습니다!',
      'notiMsgReplyTitle': '{name}님이 답장을 보냈습니다!',
      'notiMsgCheer': '{name}님이 응원 메시지를 보냈어요.',
      'notiMsgCheerWithContent': '{message}',
      'notiMsgReplyWithContent': '{message}',
      'notiMsgNestInvite': '{name}님이 \'{nestName}\' 둥지에 초대했습니다!',
      'notiMsgNestInviteAccept': '\'{nestName}\' 둥지 초대를 수락했습니다.',
      'notiMsgNestInviteReject': '\'{nestName}\' 둥지 초대를 거절했습니다.',
      'notiMsgNestDonation': '[{nestName}] 둥지에서 {name}님이 가지 {amount}개를 기부했습니다!',
      'notiMsgNestUpgrade': '🎉 [{nestName}] 둥지가 레벨 {level}로 업그레이드 되었습니다!',
      'notiMsgMemoLike': '❤️ {name}님이 내 메모에 하트를 보냈어요!',
      'notiMsgReportResultDone':
          '신고하신 메모가 삭제 조치되었습니다. 건전한 커뮤니티를 위해 힘써주셔서 감사합니다.',
      'notiMsgReportResultSuspend':
          '신고하신 회원이 {duration} 정지 처리되었습니다. 보상으로 100가지가 지급되었습니다.',
      'notiMsgReportResultReject': '신고가 반려되었습니다. 사유: {reason}',
      'notiMsgReportViolator': '작성하신 메모가 신고 접수되어 커뮤니티 가이드라인 위반으로 삭제되었습니다.',
      'notiMsgReferralReward': '추천인 보상으로 100가지를 획득했습니다!',
      'notiMsgChallenge': '{completedStatus}: {title}',
      'friendRejectShort': '친구 요청 거절',
      'cheerMessage': '응원 메시지',
      'characterEvolutionTitle': '캐릭터 진화',
      'challengeComplete': '도전 완료',
      'referralReward': '보상',
      'refreshShopTitle': '상점 새로고침',
      'refreshShopDesc': '광고를 보고 오늘의 상점 상품을 새로고침 하시겠습니까?',
      'refreshShopSuccess': '상점 상품이 새로고침 되었습니다! ✨',
      'refreshShopFreeTitle': '무료 새로고침',
      'refreshShopFreeDesc': '하루에 한 번 제공되는 무료 새로고침을 사용하시겠습니까?',
      'refreshShopLimitTitle': '제한 도달',
      'refreshShopLimitDesc': '오늘은 더 이상 새로고침할 수 없습니다. (무료 1회 + 광고 3회)',
      'shop_tutorial_1_title': "오늘의 상점 🎁",
      'shop_tutorial_1_text':
          "매일 밤 12시, 새로운 보물들이 찾아와! 🎁✨\n랜덤 아이템들로 나만의 멋진 방과 캐릭터를 꾸며봐!",
      'shop_tutorial_refresh_title': "상점 새로고침 🔄",
      'shop_tutorial_refresh_text':
          "상점의 아이템이 마음에 들지 않아? 새로운 아이템들로 다시 불러올 수 있어! (매일 무료 1회 + 광고 3회)",
      'shop_tutorial_2_title': "가지가 부족할 땐? 📽️",
      'shop_tutorial_2_text':
          "찜해둔 가구가 눈앞에 있어? 광고 보고 가지 보너스를 받아서 꿈꾸던 나만의 방을 더 빨리 완성해 봐!",
      'deco_tutorial_filter_title': "선물 찾기 🔍",
      'deco_tutorial_filter_text': "'보유 상품만 보기'를 누르면 방금 받은 선물을 쉽게 찾을 수 있어!",
      'deco_tutorial_select_title': "소품 선택하기 ✨",
      'deco_tutorial_select_text': "방금 받은 선물을 터치해서 방에 배치해보자!",
      'deco_tutorial_memo_title': "메모 남기기 📝",
      'deco_tutorial_memo_text':
          "메모를 적으면 친구들이 내 방에 방문했을 때 확인할 수 있어!\n오늘의 기분이나 친구에게 전하고 싶은 말을 남겨볼까?",
      'deco_tutorial_save_title': "방 저장하기 💾",
      'deco_tutorial_save_text': "방이 마음에 들게 꾸며졌다면 '저장' 버튼을 눌러줘!",
      'deco_tutorial_move_title': "마음대로 배치하기 ✨",
      'deco_tutorial_move_text': "선택한 소품을 원하는 위치로 드래그해서 옮겨봐! 자유롭게 방을 꾸밀 수 있어.",
      'deco_tutorial_memo_place_title': "메모 배치하기 📝",
      'deco_tutorial_memo_place_text':
          "작성한 메모도 원하는 위치로 옮길 수 있어! 보기 좋은 곳에 배치해봐.",
      'write_tutorial_blur_title': "비밀 유지 모드 🤫",
      'write_tutorial_blur_text':
          "상단 버튼으로 내용을 뿌옇게 가릴 수 있어! 누구에게도 보이고 싶지 않은 비밀 이야기를 쓸 때 유용해.",
      'write_tutorial_draft_title': "잠시 멈춰도 괜찮아 📝",
      'write_tutorial_draft_text':
          "작성하던 내용을 임시저장할 수 있어. 바쁠 때는 일단 저장해두고 나중에 다시 써도 돼!",
      'write_tutorial_mood_title': "오늘의 기분은? ✨",
      'write_tutorial_mood_text':
          "오늘의 기분을 골라봐! 방꾸미기 - 이모티콘에서 선택한 이모티콘들을 여기서 사용할 수 있어.",
      'write_tutorial_free_title': "나의 이야기 적기 ✍️",
      'write_tutorial_free_text':
          "이제 여기에 너의 소중한 이야기들을 자유롭게 적어봐!\n(튜토리얼 일기는 실제로 저장되지 않아 안심해도 돼! ✨)\n\n아 참! 내용은 10글자 이상 적어야 저장할 수 있어~ ✨",
      'write_tutorial_save_title': "일기 저장하기 💾",
      'write_tutorial_save_text':
          "이야기를 다 적었다면 이 버튼을 눌러서 완료해줘!\n너를 위한 특별한 선물이 기다리고 있을지도 몰라! 🎁",
      'main_tutorial_diary_title': "오늘의 첫 일기 쓰기 ✍️",
      'main_tutorial_diary_text':
          "안녕! Morni에 온 걸 환영해. 오늘 너의 마음은 어때? 여기를 눌러서 첫 기록을 남겨봐!",
      'main_tutorial_deco_title': "선물 확인하기 🎁",
      'main_tutorial_deco_text': "방금 받은 선물을 방에 배치해볼까?\n'방 꾸미기' 버튼을 눌러봐!",
      'main_tutorial_shop_title': "상점 구경하기 🛍️",
      'main_tutorial_shop_text': "방 꾸미기 실력이 대단한걸! 이제 상점에서 더 많은 아이템을 구경해보자!",
      'tutorial_complete_reward_title': "튜토리얼 완료 보상",
      'tutorial_complete_reward_desc': "튜토리얼 완료 보상으로 50가지를 선물해드려요!",
      'skip_tutorial_title': "튜토리얼 종료",
      'skip_tutorial_desc': "튜토리얼을 종료하시겠습니까?\n종료 시 튜토리얼 완료 보상을 받으실 수 없어요.",
      'social_tutorial_title': "친구와 함께 놀자! 🤝",
      'social_tutorial_text':
          "다른 친구들은 방을 어떻게 꾸몄을까? 친구를 추가해봐! 친구의 연속 일기 일수도 확인하고 방 구경도 가보자. 마음에 드는 방이 있다면 슬쩍 참고해 봐도 좋아!",
      'nest_tutorial_title': "둥지에서 복작복작! 🪹",
      'nest_tutorial_text':
          "더 끈끈한 사이를 원해? 둥지에서 친구들과 일기 일수를 공유하고, 서로 깨워주며 '오늘의 한마디'를 나눠봐. 둥지가 커질수록 가지 보너스도 커져!",
      'archive_tutorial_title': "소중한 기록들 📅",
      'archive_tutorial_text':
          "기록에서는 네가 쓴 소중한 기록들을 확인할 수 있어. 매일의 기분을 달력에서 한눈에 모아보자!",
    },
    'ja': {
      'settings': '設定',
      'account': 'アカウント',
      'changeNickname': 'ニックネーム変更',
      'email': 'メール',
      'security': 'セキュリティ',
      'biometricAuth': '生体認証',
      'biometricAuthDescEnabled': '生体認証が必要です',
      'biometricAuthDescDisabled': '生体認証でアプリを保護',
      'changePassword': 'パスワード変更',
      'appSettings': 'アプリ設定',
      'writingBlur': '日記のボかし',
      'writingBlurDescEnabled': 'デフォルトで内容を隠す',
      'writingBlurDescDisabled': 'デフォルトで内容を表示',
      'notificationSettings': '通知設定',
      'language': '言語',
      'info': '情報',
      'versionInfo': 'バージョン情報',
      'termsOfService': 'サービス利用規約',
      'privacyPolicy': 'プライバシーポリシー',
      'termsAndPrivacy': '利用規約',
      'faq': 'よくある質問',
      'support': 'お問い合わせ',
      'logout': 'ログアウト',
      'deleteAccount': '退会',
      'nicknamePlaceholder': 'ニックネームを入力',
      'cancel': 'キャンセル',
      'change': '変更',
      'confirm': 'OK',
      'retry': 'リトライ',
      'update': 'アップデート',
      'later': '後で',
      'updateNotice': 'アップデートのお知らせ',
      'error': 'エラー',
      'nicknameLengthError': 'ニックネームは2文字以上である必要があります',
      'nicknameTakenError': '既に使用されているニックネームです',
      'korean': '韓国語',
      'english': '英語',
      'japanese': '日本語',
      'selectLanguage': '言語選択',
      'collectMyMemos': 'マイメモを集める',
      'myPage': 'マイページ',
      'diaryWritingInfo': '日記作成情報',
      'branch': 'ブランチ',
      'pointHistoryTitle': 'ブランチ利用履歴',
      'noPointHistory': 'ブランチの利用履歴がありません。',
      'historyPurchaseTheme': 'テーマ購入',
      'historyPurchaseBackground': '背景購入',
      'historyPurchaseWallpaper': '壁紙購入',
      'historyPurchaseProp': '小物購入',
      'historyPurchaseEmoticon': '絵文字購入',
      'historyPurchaseFloor': '床購入',
      'historyPurchaseWindow': '窓購入',
      'historyPurchaseCharacterItem': 'キャラアイテム購入',
      'historyDiaryReward': '日記作成報酬',
      'historyAdReward': '広告視聴報酬',
      'historyChallengeReward': 'チャレンジ達成',
      'historyDonation': '寄付',
      'historyNestReward': '今日の一言報酬',
      'historyShopTutorialReward': 'ショップチュートリアル報酬',
      'historyStickyNote': 'メモ作成',
      'home': 'ホーム',
      'challenge': 'チャレンジ',
      'friends': '友達',
      'shop': 'ショップ',
      'buyItem': '購入する',
      'todayShop': '今日のショップ',
      'allItems': '全商品',
      'newItems': '新アイテム',
      'writeDiary': '日記を書く',
      'wallpaper': '壁紙',
      'background': '背景',
      'prop': '小物',
      'floor': '床',
      'character': 'キャラクター',
      'emoticon': '絵文字',
      'watchAdGetBranch': '広告を見てブランチを獲得',
      'completed': '日記作成完了',
      'watch': '見る',
      'unowned': '未保有',
      'purchaseConfirm': '{item}を購入しますか？',
      'salePrice': 'SALE! {original} -> {discounted} ブランチ',
      'notEnoughBranch': 'ブランチが不足しています。',
      'purchaseSuccess': '{item}を購入しました。',
      'decorate': '模様替え',
      'owned': '保有中',
      'sale': 'SALE',
      'notifications': '通知',
      'markAllAsRead': 'すべて既読',
      'loadingNotifications': '通知を読み込んでいます',
      'pleaseWait': '少々お待ちください',
      'errorLoadingNotifications': '通知の読み込み中にエラーが発生しました',
      'tryAgainLater': 'しばらくしてからもう一度お試しください',
      'noNotifications': '通知がありません',
      'noNotificationsDesc': '新しいお知らせがあればここでお伝えします',
      'replyFrom': '{username}さんの返信',
      'cheerFrom': '{username}さんの応援',
      'wakeUpAlert': '起床通知',
      'nestPokeAlert': 'ツンツン通知',
      'friendRequest': '友達申請',
      'accept': '承諾',
      'reject': '拒絶',
      'replyCompleted': '返信完了',
      'reply': '返信',
      'free': '無料',
      'ad': '広告',
      'skip': 'スキップ',
      'stickyNoteHint': '短いメッセージを残してください',
      'decorateRoom': '部屋を飾る',
      'decorationSaved': '設定が保存されました！',
      'saveFailed': '保存失敗',
      'save': '保存',
      'memo': 'メモ',
      'noProps': '購入した小物がありません。ショップで購入してみてください',
      'stickyNoteLimit': 'メモは一日一回だけ作成できます。',
      'noStickyNote': '保有しているメモがありません。ショップで購入してください',
      'deleteStickyNote': 'メモを削除しますか？',
      'stickyNoteAdded': 'メモが追加されました！',
      'notEnoughPoints': 'ブランチが不足しています。',
      'myReferralCode': '自分の招待コード',
      'referralCodeCopied': '招待コードがコピーされました',
      'greetingMorning': 'おはようございます',
      'greetingAfternoon': 'こんにちは！',
      'greetingEvening': 'こんばんは！',
      'consecutiveDays': '{days}日間連続記録中',
      'nicknameIntro': 'こんにちは！使用するニックネームを入力してください。',
      'start': 'はじめる',
      'kakaoLogin': 'カカオログイン',
      'appleLogin': 'Appleログイン',
      'nicknameChanged': 'ニックネームが変更されました！',
      'errorSavingSettings': '設定の保存中にエラーが発生しました: ',
      'enterNewNickname': '新しいニックネーム入力',
      'friendsTitle': '友達',
      'friendsCount': '{count}人',
      'addFriendEmpty': '友達を追加してみてください',
      'newFriendRequests': '新しい友達申請',
      'friendRequestSent': '{nickname}さんに友達申請を送りました',
      'youBecameFriends': '{nickname}さんと友達になりました',
      'enterFriendNickname': '友達のニックネームを入力',
      'request': '申請',
      'invite': '招待',
      'userNotFound': '該当するニックネームのユーザーが見つかりません。',
      'selfRequestError': '自分自身に友達申請は送れません。',
      'addFriendButton': '+ 友達追加',
      'friendRequestRejection': '友達申請を拒否しました',
      'wakeUp': '起こす',
      'written': '作成完了',
      'wakeUpSuccess': '{nickname}さんを起こしました！',
      'wakeUpFailed': '起こすのに失敗しました',
      'secondsUnit': '{seconds}秒',
      'challengesTitle': 'チャレンジ',
      'challengesProgress': 'チャレンジ達成数',
      'challengeCompleted': 'チャレンジ達成！',
      'challengeDetailCurrent': '現在',
      'challengeDetailTarget': '目標',
      'challengeDetailInfo': 'チャレンジ詳細',
      'challengeDetailWarningTitle': '注意事項',
      'challengeDetailWarningDesc': '一日でも欠かすと連続記録がリセットされます！',
      'challengeDetailCurrentRecord': '現在の記録',
      'challengeDetailRemaining': '同じ系列の残りチャレンジ',
      'challengeDetailReward': '報酬',
      'challengeDetailCurrentLabel': '現在',
      'challenge_dawn_start_title': '夜明けの始まり',
      'challenge_dawn_start_desc': '午前6時までに日記を1つ書く',
      'challenge_steady_habit_title': '地道な習慣',
      'challenge_steady_habit_desc': '3日間連続で日記を書く',
      'challenge_morning_person_title': '真の朝型人間',
      'challenge_morning_person_desc': '7日間連続で日記を書く',
      'challenge_rich_room_title': '豊かな部屋',
      'challenge_rich_room_desc': '小物を3つ以上購入する',
      'challenge_social_king_title': 'ソーシャルキング',
      'challenge_social_king_desc': '友達を5人作る',
      'challenge_diary_master_title': '日記マスター',
      'challenge_diary_master_desc': '累計で日記を30個書く',
      'challenge_streak_14_title': '2週間の記録',
      'challenge_streak_14_desc': '14日間連続で日記を書く',
      'challenge_streak_21_title': '3週間の記録',
      'challenge_streak_21_desc': '21日間連続で日記を書く',
      'challenge_streak_30_title': '一ヶ月の奇跡',
      'challenge_streak_30_desc': '30日間連続で日記を書く',
      'challenge_friend_1_title': '初めての友達',
      'challenge_friend_1_desc': '最初の友達を作る',
      'challenge_friend_10_title': '人気者',
      'challenge_friend_10_desc': '友達を10人作る',
      'challenge_friend_20_title': '顔が広い',
      'challenge_friend_20_desc': '友達を20人作る',
      'challenge_prop_1_title': '初めての小物',
      'challenge_prop_1_desc': '小物を1つ購入する',
      'challenge_prop_5_title': '模様替えの卵',
      'challenge_prop_5_desc': '小物を5つ購入する',
      'challenge_prop_10_title': 'マキシマリスト',
      'challenge_prop_10_desc': '小物を10つ購入する',
      'challenge_fashion_3_title': 'ファッショニスタ',
      'challenge_fashion_3_desc': 'キャラアイテムを3つ購入する',
      'challenge_fashion_5_title': 'トレンドセッター',
      'challenge_fashion_5_desc': 'キャラアイテムを5つ購入する',
      'challenge_bg_1_title': '気分転換',
      'challenge_bg_1_desc': '背景を1つ購入する',
      'challenge_bg_3_title': 'ムードメーカー',
      'challenge_bg_3_desc': '背景を3つ購入する',
      'challenge_level_2_title': '初めての成長',
      'challenge_level_2_desc': 'キャラレベル2達成',
      'challenge_level_3_title': 'すくすく成長',
      'challenge_level_3_desc': 'キャラレベル3達成',
      'challenge_level_4_title': 'あともう少し',
      'challenge_level_4_desc': 'キャラレベル4達成',
      'challenge_level_5_title': '急成長',
      'challenge_level_5_desc': 'キャラレベル5達成',
      'challenge_memo_1_title': '初めてのメモ',
      'challenge_memo_1_desc': '最初のメモを作成',
      'challenge_memo_3_title': 'メモ収集家',
      'challenge_memo_3_desc': 'メモを3つ作成',
      'challenge_memo_10_title': 'メモマニア',
      'challenge_memo_10_desc': 'メモを10個作成',
      'challenge_memo_30_title': 'メモマスター',
      'challenge_memo_30_desc': 'メモを30個作成',
      'deleteAccountConfirmDesc': '本当に退会しますか？すべてのデータが永久に削除されます。',
      'passwordConfirmHint': 'パスワード確認',
      'deleteAccountConsent': '注意事項を確認し、退会に同意します。',
      'noDiaryForDay': 'この日は日記を書きませんでした。',
      'diaryRecordForDay': '{date}の記録',
      'biometricAuthReasonPastRecords': '過去の記録を確認するために認証が必要です。',
      'biometricAuthFailed': '生体認証に失敗しました。',
      'noMemos': '作成したメモがありません',
      'myMemos': 'マイメモ',
      'fullDateFormat': '{year}年{month}月{day}日（{weekday}）',
      'monthDayFormat': '{month}月{day}日',
      'monthDayFormatWithWeekday': '{month}月{day}日（{weekday}）',
      'state_egg': '卵 🥚',
      'state_cracking': 'ひび割れた卵 🥚✨',
      'state_hatching': '孵化中 🐣',
      'state_baby': 'ヒナ 🐥',
      'state_young': '若鳥 🐦',
      'state_adult': '成鳥 🕊️',
      'state_sleeping': '睡眠中 💤',
      'weekday_mon': '月',
      'weekday_tue': '火',
      'weekday_wed': '水',
      'weekday_thu': '木',
      'weekday_fri': '金',
      'weekday_sat': '土',
      'weekday_sun': '日',
      'noQuestion': '質問がありません。',
      'previous': '前へ',
      'next': '次へ',
      'gift_popup_title': '特別なプレゼント 🎁',
      'gift_popup_welcome': '初訪問おめでとうございます！ 🎉',
      'gift_popup_desc': '特別なプレゼントが届きました。',
      'receive': '受け取る',
      'characterInfo': 'キャラクター情報',
      'biometricErrorTitle': '生体認証失敗',
      'biometricErrorDesc': '認証に失敗しました。再試行するかログアウトしてください。',
      'logoutTitle': 'ログアウト',
      'logoutDesc': 'ログアウトしますか？',
      'deleteAccountTitle': '退会',
      'deleteAccountDesc': '退会しますか？データは復旧できません。',
      'pageNotFound': 'ページが見つかりません',
      'addFriendTitle': '友達追加',
      'cheerMessageTitle': '応援メッセージ',
      'exitWritingTitle': '作成を中止しますか？',
      'exitWritingDesc': '中止すると内容は保存されません。',
      'keepWriting': '続ける',
      'stop': '中止',
      'sentMessagesTitle': '送信済みメッセージ',
      'purchaseTitle': 'アイテム購入',
      'purchaseCompleteTitle': '購入完了',
      'levelUpTitle': '🎊 おめでとうございます！ 🎊',
      'levelUpDesc': 'キャラクターが成長しました！',
      'continueGrowth': 'これからも成長を見守ってください。',
      'maxLevel': '最大レベル',
      'adRewardTitle': 'ブランチ獲得！',
      'adRewardDesc': '報酬として20ブランチを獲得しました！',
      'deleteFriendTitle': '友達削除',
      'deleteFriendDesc': '友達を削除しますか？',
      'reportTitle': '通報する',
      'report': '通報',
      'ok': 'OK',
      'close': '閉じる',
      'bonusAdOfferTitle': '🎁 ボーナス獲得！',
      'bonusAdOfferDesc': '広告視聴で20ブランチをプレゼント！',
      'bonusAdOfferWarning': '※最後まで視聴しないと報酬は受け取れません。',
      'watchAd': '広告を見る',
      'item_name_default': 'きほん',
      'item_name_stripe': 'ストライプ',
      'item_name_check': 'チェック',
      'item_name_dot': 'ドット',
      'item_name_flower_sky': 'はなぞら',
      'item_name_pink_lace': 'ピンクレース',
      'item_name_red_heart': '赤いハート',
      'item_name_colorful_hexagon': 'カラフルヘキサゴン',
      'item_name_Space_Background': 'うちゅう',
      'item_name_Castle_Stone_Wall': 'じょうへきの かべかみ',
      'item_name_lego_wallpaper': 'ブロックのかべかみ',
      'item_name_DarkPanel': 'ダークパネル',
      'item_name_IvoryClassic': 'アイボリークラシック',
      'item_name_light': 'ライト',
      'item_name_happy': 'ハッピー',
      'item_name_normal': 'ふつう',
      'item_name_sad': 'かなしい',
      'item_name_love': 'だいすき',
      'item_name_angry': 'おこる',
      'item_name_awkward': 'こまる',
      'item_name_move': 'かんどう',
      'item_name_sleep': 'ねむい',
      'item_name_blue_moon': 'あおい月',
      'item_name_blue_moon2': 'あおい月2',
      'item_name_golden_sun': 'おうごんの太陽',
      'item_name_starry_night': 'ほしぞら',
      'item_name_alarm_clock': 'めざましどけい',
      'item_name_wood_desk': 'もくざいのつくえ',
      'item_name_book_desk': 'しょけんだい',
      'item_name_wooden_desk_sprite': 'もくざいのつくえ2',
      'item_name_space_desk': 'うちゅうのつくえ',
      'item_name_space_desk2': 'うちゅうのつくえ2',
      'item_name_space_drawer': 'うちゅうのタンス',
      'item_name_space_drawer2': 'うちゅうのタンス2',
      'item_name_wood_chair': 'もくざいのいす',
      'item_name_wood_bed': 'もくざいのベッド',
      'item_name_space_chair': 'うちゅうのいす',
      'item_name_space_bed': 'うちゅうのベッド',
      'item_name_pogeun_sofa': 'ふわふわソファ',
      'item_name_cozy_bean': 'おひるねソファ',
      'item_name_pot_1': 'うえきばち',
      'item_name_analog_clock': 'アナログどけい',
      'item_name_white_bear': 'しろくまのぬいぐるみ',
      'item_name_pink_chair': 'ピンクのいす',
      'item_name_blue_chair': 'あおいいす',
      'item_name_mug_cup': 'マグカップ',
      'item_name_wood_cup': 'き のコップ',
      'item_name_cloud_watch': 'くものとけい',
      'item_name_red_carpet': 'レッドカーペット',
      'item_name_sticky_note': 'メモ',
      'item_name_wood': 'もくざいのゆか',
      'item_name_wood2': 'もくざいのゆか2',
      'item_name_pink_wood': 'ピンクのゆか',
      'item_name_peach_break': 'ピーチピーチ',
      'item_name_pink_carpet': 'ピンクのカーペット',
      'item_name_alokdalok': 'カラフル',
      'item_name_castle_stone': 'おしろのゆか',
      'item_name_space_floor': 'うちゅうのゆか',
      'item_name_lego_book_desk': 'ブロックの つくえ',
      'item_name_lego_chair': 'ブロックのいす',
      'item_name_lego_clock': 'ブロックのとけい',
      'item_name_lego_cloth_desk': 'ブロックのヌノつくえ',
      'item_name_lego_desk': 'ブロックのつくえ',
      'item_name_lego_door': 'ブロックのドア',
      'item_name_lego_flower': 'ブロックのはな',
      'item_name_lego_frame': 'ブロックのがくぶち',
      'item_name_lego_frame2': 'ブロックのがくぶち2',
      'item_name_lego_game_machine': 'ブロックのゲームき',
      'item_name_lego_lamp': 'ブロックのランプ',
      'item_name_lego_mailbox': 'ブロックのポスト',
      'item_name_lego_piano': 'ブロックのピアノ',
      'item_name_lego_sink': 'ブロックのせんめんたい',
      'item_name_lego_floor': 'ブロックのゆか',
      'item_name_DarkWood_Floor': 'くらい もくざいのゆか',
      'item_name_lego_lug': 'ブロックのラグ',
      'item_name_wall_lamp': 'かべのランプ',
      'item_name_warm_lamp': 'あたたかいランプ',
      'login': 'ログイン',
      'signup': 'しんきとうろく',
      'emailPlaceholder': 'メールアドレス',
      'passwordPlaceholder': 'パスワード',
      'currentPassword': 'げんざいのかパスワード',
      'currentPasswordRequired': 'げんざいのパスワードをにゅうりょくしてください',
      'newPasswordHint': 'あたらしいパスワード (6じ いじょう)',
      'newPasswordRequired': 'あたらしいパスワードをにゅうりょくしてください',
      'passwordConfirmRequired': 'パスワード(かくにん)をにゅうりょくしてください',
      'passwordChangedSuccess': 'パスワードをへんこうしました',
      'currentPasswordMismatch': 'げんざいのパスワードが まちがっています',
      'requireRecentLogin': 'あんぜんのため、さいどログインしてください',
      'loginWithGoogle': 'Googleでログイン',
      'loginWithKakao': 'Kakaoでログイン',
      'loginWithApple': 'Appleでログイン',
      'loginWithID': 'IDでログイン',
      'idLogin': 'IDログイン',
      'guestLogin': 'おためしログイン',
      'guestMigrationTitle': 'きろくを ほぞんしますか？',
      'friendSocialLoginTitle': 'ともだちと つながるには ログインが必要です',
      'nestSocialLoginTitle': 'す を つくるには ログインが必要です',
      'guestLoginMigrationDesc': 'ログインすると',
      'guestLoginBullet1': 'きろくが きえません',
      'guestLoginBullet2': 'ほかのききでも つかえます',
      'guestLoginBullet3': 'ともだちと きろくを シェアできます',
      'guestLoginBullet4': 'す を せいちょう させられます',
      'availableAfterSocialLogin': 'ログインごに りようできます',
      'noAccountSignup': 'アカウントがありませんか？ しんきとうろく',
      'alreadyHaveAccountLogin': 'アカウントをおもちですか？ ログイン',
      'emailRequired': 'メールアドレスをにゅうりょくしてください',
      'emailInvalid': 'メールアドレスのけいしきが ただしくありません',
      'passwordRequired': 'パスワードをにゅうりょくしてください',
      'passwordLengthError': 'パスワードは 6じ いじょうにしてください',
      'namePlaceholder': 'おなまえ',
      'nameRequired': 'おなまえをにゅうりょくしてください',
      'passwordConfirmPlaceholder': 'パスワード(かくにん)',
      'passwordMismatch': 'パスワードが いっちしません',
      'signupSuccess': 'とうろくが かんりょうしました！ログインしてください。',
      'loginError': 'ログインしっぱい',
      'signupError': 'とうろくしっぱい',
      'introTitle': 'Morni',
      'introSubtitle': 'あさを いっしょにすごす あなたのメイト',
      'welcomeTitle': 'ようこそ！',
      'welcomeDesc': 'ニックネームと しょうかいコード(あれば)をいれてください。',
      'nicknameLabel': 'ニックネーム',
      'nicknamePlaceholder2': 'ニックネームをいれてください',
      'referralLabel': 'しょうかいコード (にんい)',
      'referralPlaceholder': 'しょうかいコードがあれば いれてください',
      'referralReward1': 'ともだちと いっしょに ',
      'referralReward2': '100こ もらえます！',
      'serviceNotification': 'サービスつうち',
      'morningDiaryNoti': 'あさの にっきつうち',
      'morningDiaryNotiDesc': 'まいあさ にっきをわすれないように おしらせします',
      'activityNotification': 'かつどうつうち',
      'wakeUpNoti': 'おこすつうち',
      'wakeUpNotiDesc': 'ともだちが おこしてくれたら おしらせします',
      'cheerMessageNoti': 'おうえんメッセージつうち',
      'cheerMessageNotiDesc': 'ともだちが おうえんメッセージをくれたら おしらせします',
      'friendNotification': 'ともだちつうち',
      'friendRequestNoti': 'ともだちリクエストつうち',
      'friendRequestNotiDesc': 'あたらしい ともだちリクエストがきたら おし知らせします',
      'friendAcceptNoti': 'ともだちしょうにんつうち',
      'friendAcceptNotiDesc': 'あいてが リクエストをうけいれたら おしらせします',
      'friendAcceptNotiTitle': 'ともだちリクエストしょうにん',
      'friendAcceptNotiBodyBasic': 'ともだちリクエストが しょうにんされました。',
      'friendAcceptNotiBodyNamed': '{name}さんが リクエストをしょうにんしました。',
      'friendRejectNoti': 'ともだちきょひつうち',
      'friendRejectNotiDesc': 'リクエストが きょひされたら おしらせします',
      'notificationTime': 'つうちじかんの せってい',
      'timePickerHour': 'じ',
      'timePickerMinute': 'ふん',
      'nestNotification': 'す のつうち',
      'nestInviteNoti': 'す へのしょうたいつうち',
      'nestInviteNotiDesc': 'す にしょうたいされたら おしらせします',
      'nestDonationNoti': 'ブランチきふつうち',
      'nestDonationNotiDesc': 'メンバーが ブランチをきふしたら おしらせします',
      'tempSave': 'いちじほぞん',
      'saveDraft': 'いちじほぞん',
      'saveDraftSuccess': 'いちじほぞん しました。 📝',
      'saveDraftError': 'いちじほぞん中に エラーがおきました。 ⚠️',
      'saveDiarySuccess': 'ほぞんしました！キャラクターがおきました！ ☀️',
      'saveDiaryError': 'ほぞん中に エラーがおきました。 ⚠️',
      'diaryCompletionTitle': 'キャラクターがおきました！',
      'diaryCompletionDesc': 'キャラクターの いちにちが はじまりました！',
      'branchEarned': '+{amount}こ ゲット',
      'exitConfirmation': 'さくせいを ちゅうししますか？',
      'exitConfirmationDesc': 'かいた内容は ほぞんされません。',
      'writingHint': 'いま おもいついたことを じゆうにかいてみてください。',
      'todayQuestion': 'きょうのしつもん',
      'moreWriting': 'もう少しだけ かいてみてください！ ✍️',
      'authRequiredForSave': 'あんぜんに ほぞんするため、にんしょうが必要です',
      'authFailedForSave': 'にんしょうにしっぱいしたため ほぞんできません。 🔒',
      'diaryContent': 'にっきの内容',
      'encryptedDiary': 'あんごうかされた にっき',
      'diaryLoadError': 'にっきを よみこめませんでした。',
      'noDiaryContent': 'にっきの内容が ありません。',
      'emotionalAnalysis': 'かんじょうぶんせき',
      'totalDiaries': 'にっきごうけい',
      'consecutiveDaysLabel': 'れんぞくきろく',
      'days': 'にち',
      'edit': 'しゅうせい',
      'yes': 'はい',
      'no': 'いいえ',
      'equipped': 'そうび中',
      'stampEquipped': 'そうび',
      'unequipped': 'そうびかいじょ',
      'item_name_heart_glass': 'ハートのめがね',
      'item_name_blue_ribbon': 'あおいリボン',
      'item_name_pink_mupler': 'ピンクのマフラー',
      'item_name_necktie': 'ネクタイ',
      'item_name_plogeyes': 'カエルのめ',
      'item_name_sprout': 'ふたば',
      'item_name_crown': 'おうかん',
      'item_name_wood_glass': 'き のめがね',
      'item_name_space_clothes': 'うちゅうふく',
      'item_name_prog_clothes': 'カエルスーツ',
      'item_name_superb_bird_clothes': 'ごくらくちょうのふく',
      'item_name_humming_bird_clothes': 'ハチドリのふく',
      'item_name_knight_helm': 'きしのカブト',
      'item_name_castle_candle': 'おしろのしょくだい',
      'item_name_castle_knight_statue': 'きしのぞう',
      'item_name_castle_treasure_chest': 'たからばこ',
      'item_name_castle_gargoyle_statue': 'ガーゴイルぞう',
      'decorateCharacter': '着せ替え',
      'unequipAll': '全解除',
      'removeAllProps': '全リセット',
      'showOwnedOnly': 'もっている アイテムだけ見る',
      'bulkPurchase': 'まとめてかう',
      'bulkPurchaseConfirm': 'まだ もっていないアイテムがあります。\nいっかつで 購入しますか？',
      'totalPrice': 'ごうけい: ',
      'purchaseAndSaveSuccess': 'こうにゅうと ほぞんが できました！ ✨',
      'all': 'ぜんぶ',
      'head': 'あたま',
      'face': 'かお',
      'clothes': 'からだ',
      'accessory': 'かざり',
      'viewDiaryContent': 'にっきをみる',
      'suspensionTitle': 'りようせいげん',
      'unsuspendTitle': 'せいげんとき',
      'suspensionContent': 'ガイドラインいはんのため、サービスのごりようが せいげんされています。',
      'remainingTimeTitle': 'のこりじかん',
      'permanentSuspension': 'えいきゅうせいげん',
      'daysRemaining': '{days}にち {hours}じかん のこり',
      'hoursRemaining': '{hours}じかん {minutes}ふん のこり',
      'minutesRemaining': '{minutes}ふん のこり',
      'suspensionReason': 'りゆう: {reason}',
      'reason_community_violation': 'ガイドラインいはん',
      'sendCheerMessage': 'おうえんする',
      'resendAfterSeconds': '{seconds}びょうごに さいそうしん',
      'sentHistory': 'りれき',
      'friend': 'ともだち',
      'cheerMessageHint': 'ともだちに おうえんのことばを のこしてください',
      'cheerMessageSent': 'おうえんメッセージを おくりました！ 💌',
      'cheerMessageSendFailed': 'おうえんメッセージの そうしんに しっぱいしました。',
      'leave': 'のこす',
      'noSentMessages': 'まだ おくったメッセージがありません',
      'userReport': 'ユーザーつうほう',
      'reportReasonSelect': 'つうほうの りゆうを えらんでください。',
      'reportSubmitted': '通報を受理しました。',
      'reportError': '通報の受付中にエラーが発生しました。',
      'reportReasonInappropriate': '不適切な内容',
      'reportReasonAbusive': '暴言/差別的発言',
      'reportReasonSpam': 'スパム/広告',
      'reportReasonOther': 'その他',
      'deleteFriendConfirm': '{nickname}さんを友達リストから削除しますか？',
      'delete': '削除',
      'friendDeleted': '友達が削除されました。',
      'friendDeleteError': '友達の削除中にエラーが発生しました。',
      'nest': '巣',
      'nestList': '巣リスト',
      'participatingNests': '参加中の巣',
      'myNests': '作成した巣',
      'createNest': '+ 巣を作る',
      'nestLevel': 'Lv.{level}',
      'nestPeopleCount': '{current}/{max}人',
      'createdAt': '作成日',
      'lastActivity': '{time}前に活動',
      'todayActivity': '今日の活動',
      'yesterdayActivity': '昨日の活動',
      'hoursAgo': '{hours}時間',
      'minutesAgo': '{minutes}分',
      'justNow': 'たった今',
      'recentActivity': '最近の活動',
      'createNestTitle': '巣を作る',
      'nestName': '巣の名前',
      'enterNestName': '巣の名前を入力してください',
      'maxPeople': '最大人数',
      'isPublic': '公開設定',
      'public': '公開',
      'private': '非公開',
      'create': '作成',
      'unknown': '不明',
      'nestEditTitle': '巣の修正',
      'collectGajiTitle': 'ブランチ集め',
      'nestInvitePopupTitle': '巣に招待',
      'nestCreateTitle': '巣を作る',
      'nestNoParticipating': '参加中の巣がありません',
      'nestNoMyNests': '作成した巣がありません',
      'nestCreateNew': '新しい巣を作ってみましょう！',
      'nestInviteButton': '+ 巣に招待',
      'nestPlaceholderDesc': '私たちの巣の物語',
      'nestActivityJustNow': '先ほど活動',
      'nestActivityDaysAgo': '{days}日前に活動',
      'nestActivityHoursAgo': '{hours}時間前に活動',
      'nestActivityMinutesAgo': '{minutes}分前に活動',
      'nestEnter': '入場する >',
      'nestInvite': '巣に招待',
      'nestDonation': '巣に寄付',
      'nestInviteTitle': '新しい巣への招待',
      'nestLabel': '巣: {name}',
      'nestInvitePlaceholder': '招待する友達のニックネームを入力',
      'nestSelfInviteError': '自分自身は招待できません。',
      'nestUserNotFoundError': '存在しないニックネームです。',
      'nestAlreadyMemberError': '既に巣にいるユーザーです。',
      'nestInviteSent': '{nickname}さんに招待を送りました。',
      'nestInviteFailed': '招待失敗: {error}',
      'nestCollectHint': '集める数量を入力してください',
      'nestCollectButton': '集める',
      'nestInvalidAmount': '正しい数字を入力してください。',
      'nestNotEnoughGaji': '保有しているブランチより多くは集められません。',
      'nestCollectSuccessTitle': '集める完了',
      'nestCollectSuccessDesc': '報酬を獲得しました',
      'nestManageTitle': '巣の管理',
      'nestNameHint': '巣の名前を入力してください',
      'nestDescHint': '巣の説明を入力（最大15文字）',
      'nestUpdateSuccess': '巣の情報を修正しました！',
      'nestCreateSuccess': '巣が作成されました！',
      'nestMyStreak': '自分の連続記録: {days}日！',
      'nestPokeCooldown': 'あ！{seconds}秒後にもう一度ツンツンできます。',
      'nestPokeSuccess': '{nickname}さんをツンツンしました！',
      'nestPokeDescription': '{nickname}: 連続 {days}日！ (ダブルタップでツンツン)',
      'nestNoMembers': 'まだメンバーがいません。',
      'errorOccurred': 'エラーが発生しました。',
      'dayUnit': '日',
      'nestMaxCountError': '最大2つまでの巣しか作れません。',
      'nestInvalidDonateAmount': '寄付するブランチの数を正確に入力してください。',
      'nestNotEnoughGajiError': '保有しているブランチが不足しています。',
      'nestEmptyMessageError': '一言を入力してください。',
      'nestEmptyNameError': '巣の名前を入力してください。',
      'nestFullTitle': '巣の定員超過',
      'nestFullError': 'これ以上参加できません',
      'nestLeaveConfirm': '{name}の巣から本当に抜けますか？',
      'nestLeaveTitle': '巣を抜ける',
      'nestDeleteTitle': '巣を削除',
      'nestDeleteSuccess': '巣が削除されました。',
      'nestLeaveSuccess': '巣から退出しました。',
      'nestWithdraw': '抜ける',
      'nestUpgradeTitle': '巣のアップグレード',
      'nestUpgradeSuccess': '巣がレベル {level} になりました！',
      'nestUpgrade': 'アップグレード',
      'upgrade': 'アップグレード',
      'nestBuffActive': '日記作成ブランチ +{bonus}% バフ適用中！',
      'nestUpgradeNotEnoughGaji': 'ブランチが不足しています。（1000個必要）',
      'todaySpeakTitle': '今日の一言',
      'previousDayBtn': '< 前の日',
      'nextDayBtn': '次の日 >',
      'noTodaySpeakRecords': '作成した一言がありません。',
      'unknownUser': '不明なユーザー',
      'deleteTodaySpeakTitle': '削除しますか？',
      'alreadyPostedTodaySpeak': '既に今日の一言を作成しました。',
      'todaySpeakHint': '今日の一言を残してください',
      'todaySpeakWrite': '作成',
      'todaySpeakRewardTitle': '報酬獲得！',
      'todaySpeakRewardDesc': '今日の一言報酬として10ブランチを獲得しました！',
      'item_name_bubble_bubble_fish_world': 'ぷくぷくフィッシュワールド',
      'item_name_none': 'なし',
      'none': 'なし',
      'window': '窓',
      'nightlyReminderTitle': '今日の日記を書いてください！',
      'nightlyReminderBody': 'まだ日記が書かれていません。記録を途絶えさせないようにしましょう！',
      'morningReminderTitle': 'グッドモーニング！朝の日記を書く時間です ☀️',
      'morningReminderBody': '清々しい一日の始まりに日記を残しましょう！',
      'notiMsgWakeUp': '{name}さんがあなたを起こしています！',
      'notiMsgWakeUpPoke': '👉 [{nestName}] 巣で{name}さんが突つきました！',
      'notiMsgFriendRequest': '👋 {name}さんが友達申請を送りました！',
      'notiMsgFriendAccept': '{name}さんが友達申請を承認しました。',
      'notiMsgFriendReject': '{name}さんが友達申請を拒否しました。',
      'notiMsgCheerTitle': '{name}さんが応援メッセージを送りました！',
      'notiMsgReplyTitle': '{name}さんが返信を送りました！',
      'notiMsgCheer': '{name}さんが応援メッセージを送りました。',
      'notiMsgCheerWithContent': '{message}',
      'notiMsgReplyWithContent': '{message}',
      'notiMsgNestInvite': '{name}さんが「{nestName}」に招待しました！',
      'notiMsgNestInviteAccept': '「{nestName}」への招待を承諾しました。',
      'notiMsgNestInviteReject': '「{nestName}」への招待を拒否しました。',
      'notiMsgNestDonation': '[{nestName}] で{name}さんがブランチ {amount}個を寄付しました！',
      'notiMsgNestUpgrade': '🎉 [{nestName}] がレベル {level} にアップグレードされました！',
      'notiMsgMemoLike': '❤️ {name}さんがあなたのメモにハートを送りました！',
      'notiMsgReportResultReject': '通報が却下されました。理由: {reason}',
      'notiMsgReportViolator': '作成したメモが通報により規約違反として削除されました。',
      'notiMsgReferralReward': '招待報酬として100ブランチを獲得しました！',
      'notiMsgChallenge': '{completedStatus}: {title}',
      'friendRejectShort': '申請拒否',
      'cheerMessage': '応援メッセージ',
      'characterEvolutionTitle': 'キャラクター進化',
      'challengeComplete': 'チャレンジ達成',
      'referralReward': '報酬',
      'refreshShopTitle': 'ショップ更新',
      'refreshShopDesc': '広告を見て商品を更新しますか？',
      'refreshShopSuccess': '商品が更新されました！ ✨',
      'refreshShopFreeTitle': '無料更新',
      'refreshShopFreeDesc': '一日一回の無料更新を使用しますか？',
      'refreshShopLimitTitle': '制限到達',
      'refreshShopLimitDesc': '本日の更新回数を超えました。（無料1回 + 広告3回）',
      'deco_tutorial_filter_text': '保有アイテムのみ表示',
      'deco_tutorial_save_text': '保存',
      'main_tutorial_deco_text': '模様替え',
      'nest_tutorial_text': '今日の一言',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String getFormat(String key, Map<String, String> args) {
    String text = get(key);
    args.forEach((k, v) {
      text = text.replaceAll('{$k}', v);
    });
    return text;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ko', 'ja'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}